/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zapateria.main.view;

import com.zapateria.main.dto.SesionDTO;
import com.zapateria.main.util.Conexion;
import com.zapateria.main.util.Sesion;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

/**
 *
 * @author Usuario
 */
public class Escritorio extends MarcoPersonalizado {

    private static final long serialVersionUID = 5947777371087563681L;

    private static final String VISTAS = "VISTAS", ROLES = "ROLES",
            PERMISOS = "PERMISOS", USUARIOS = "USUARIOS", VENTAS = "VENTAS", CLIENTES = "CLIENTES",
            INVENTARIO = "INVENTARIO", NOMINA = "NOMINA", VENTAS2 = "VENTAS2";

    private static SesionDTO SESION_USUARIO = Sesion.obtenerSesion();

    private ifrmInventario vistaInventario;
    private ifrmNomina vistaNomina;
    private ifrmClientes vistaClientes;
    private ifrmPermisos vistaPermisos;
    private ifrmRoles vistaRoles;
    private ifrmUsuarios vistaUsuarios;
    private ifrmVentas vistaVentas;
    private ifrmVistas vistaVistas;
    private ifrmFacturas vistaFacturas;
    private ifrmVentas2 VistaVentas2;

    /**
     * Creates new form Escritorio
     */
    public Escritorio() {
        initComponents();
        this.dpEscritorio.setBorder(new ImagenFondo());
        this.menuArchivo.setVisible(false);
        this.menuPreferencias.setVisible(false);

    }

    
        
      
    public void mostrarVista(JInternalFrame ifrm) {
        if (ifrm != null && !ifrm.isShowing()) {
            dpEscritorio.add(ifrm);
            //centra el JinternalFrame
            Dimension desktopSize = dpEscritorio.getSize();
            Dimension FrameSize = ifrm.getSize();
            ifrm.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            //Abre Maximizado el JinternalFrame
             try {
                ifrm.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(ifrmVentas.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            //  ifrm.setLayout(null);
            ifrm.show();
        }else if(ifrm.isShowing()){
            mostrarMensaje("Abierto");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpEscritorio = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        barraMenuPrincipal = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuItemVentas = new javax.swing.JMenuItem();
        menuItemInventario = new javax.swing.JMenuItem();
        menuItemClientes = new javax.swing.JMenuItem();
        menuItemNomina = new javax.swing.JMenuItem();
        menuItemSalir = new javax.swing.JMenuItem();
        menuPreferencias = new javax.swing.JMenu();
        menuAdministrar = new javax.swing.JMenu();
        menuItemVistas = new javax.swing.JMenuItem();
        menuItemRoles = new javax.swing.JMenuItem();
        menuItemPermisos = new javax.swing.JMenuItem();
        menuItemUsuarios = new javax.swing.JMenuItem();
        btnVentas = new javax.swing.JMenu();
        Clientes = new javax.swing.JMenu();
        Facturacion = new javax.swing.JMenu();
        Reportes = new javax.swing.JMenu();
        Empleados = new javax.swing.JMenu();
        Nomina = new javax.swing.JMenu();
        Inventarios = new javax.swing.JMenu();
        Proveedores = new javax.swing.JMenu();
        Roles = new javax.swing.JMenu();
        Permisos = new javax.swing.JMenu();
        Vistas = new javax.swing.JMenu();
        Config = new javax.swing.JMenu();
        btnAyuda = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zapateria");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        dpEscritorio.setBackground(new java.awt.Color(0, 51, 204));
        dpEscritorio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dpEscritorio.setToolTipText("Escritorio");
        dpEscritorio.setDoubleBuffered(true);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        dpEscritorio.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpEscritorioLayout = new javax.swing.GroupLayout(dpEscritorio);
        dpEscritorio.setLayout(dpEscritorioLayout);
        dpEscritorioLayout.setHorizontalGroup(
            dpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpEscritorioLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addContainerGap(1435, Short.MAX_VALUE))
        );
        dpEscritorioLayout.setVerticalGroup(
            dpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpEscritorioLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(325, Short.MAX_VALUE))
        );

        menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/ventas.png"))); // NOI18N
        menuArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuArchivoMouseClicked(evt);
            }
        });

        menuItemVentas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        menuItemVentas.setText("Ventas");
        menuItemVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVentasActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemVentas);

        menuItemInventario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        menuItemInventario.setText("Inventario");
        menuItemInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInventarioActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemInventario);

        menuItemClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menuItemClientes.setText("Clientes");
        menuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemClientesActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemClientes);

        menuItemNomina.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        menuItemNomina.setText("Nómina");
        menuItemNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNominaActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemNomina);

        menuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemSalir);

        barraMenuPrincipal.add(menuArchivo);

        menuPreferencias.setText("Preferencias");

        menuAdministrar.setText("Administrar");

        menuItemVistas.setText("Ventanas y pestañas");
        menuItemVistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVistasActionPerformed(evt);
            }
        });
        menuAdministrar.add(menuItemVistas);

        menuItemRoles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuItemRoles.setText("Roles");
        menuItemRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRolesActionPerformed(evt);
            }
        });
        menuAdministrar.add(menuItemRoles);

        menuItemPermisos.setText("Permisos");
        menuItemPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPermisosActionPerformed(evt);
            }
        });
        menuAdministrar.add(menuItemPermisos);

        menuItemUsuarios.setText("Usuarios");
        menuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUsuariosActionPerformed(evt);
            }
        });
        menuAdministrar.add(menuItemUsuarios);

        menuPreferencias.add(menuAdministrar);

        barraMenuPrincipal.add(menuPreferencias);

        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/VENTAS.png"))); // NOI18N
        btnVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentasMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVentasMousePressed(evt);
            }
        });
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        barraMenuPrincipal.add(btnVentas);

        Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/CLIENTES.png"))); // NOI18N
        Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientesMouseClicked(evt);
            }
        });
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        barraMenuPrincipal.add(Clientes);

        Facturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/FACTURACION.png"))); // NOI18N
        Facturacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FacturacionMouseClicked(evt);
            }
        });
        barraMenuPrincipal.add(Facturacion);

        Reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/REPORTES.png"))); // NOI18N
        barraMenuPrincipal.add(Reportes);

        Empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/EMPLEADOS.png"))); // NOI18N
        Empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpleadosMouseClicked(evt);
            }
        });
        barraMenuPrincipal.add(Empleados);

        Nomina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/NOMINA.png"))); // NOI18N
        Nomina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NominaMouseClicked(evt);
            }
        });
        barraMenuPrincipal.add(Nomina);

        Inventarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/INVENTARIOS.png"))); // NOI18N
        Inventarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventariosMouseClicked(evt);
            }
        });
        barraMenuPrincipal.add(Inventarios);

        Proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/PROVEEDORES.png"))); // NOI18N
        barraMenuPrincipal.add(Proveedores);

        Roles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/ROLES.png"))); // NOI18N
        Roles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RolesMouseClicked(evt);
            }
        });
        barraMenuPrincipal.add(Roles);

        Permisos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/PERMISOS.png"))); // NOI18N
        Permisos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PermisosMouseClicked(evt);
            }
        });
        barraMenuPrincipal.add(Permisos);

        Vistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/VISTAS.png"))); // NOI18N
        Vistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VistasMouseClicked(evt);
            }
        });
        barraMenuPrincipal.add(Vistas);

        Config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/CONFIGURACION.png"))); // NOI18N
        barraMenuPrincipal.add(Config);

        btnAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/AYUDA.png"))); // NOI18N
        btnAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAyudaMouseClicked(evt);
            }
        });
        barraMenuPrincipal.add(btnAyuda);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/SALIR.png"))); // NOI18N
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        jMenu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu9ActionPerformed(evt);
            }
        });
        barraMenuPrincipal.add(jMenu9);

        setJMenuBar(barraMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpEscritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        // Aplicando los permisos disponibles para el usuario que inició la sesión.
        menuItemVistas.setEnabled(SESION_USUARIO.isVistaPermitida(VISTAS));
        menuItemRoles.setEnabled(SESION_USUARIO.isVistaPermitida(ROLES));
        menuItemPermisos.setEnabled(SESION_USUARIO.isVistaPermitida(PERMISOS));
        menuItemUsuarios.setEnabled(SESION_USUARIO.isVistaPermitida(USUARIOS));
        //menuItemVentas.setEnabled(SESION_USUARIO.isVistaPermitida(VENTAS));
        menuItemInventario.setEnabled(SESION_USUARIO.isVistaPermitida(INVENTARIO));
        menuItemClientes.setEnabled(SESION_USUARIO.isVistaPermitida(CLIENTES));
        menuItemNomina.setEnabled(SESION_USUARIO.isVistaPermitida(NOMINA));
        
        btnVentas.setEnabled(SESION_USUARIO.isVistaPermitida(VENTAS));
        btnAyuda.setEnabled(SESION_USUARIO.isVistaPermitida(VENTAS2));

        //Instanciando las vistas si el menu que las activa esta habilitado
        if (menuItemVistas.isEnabled()) {
            vistaVistas = new ifrmVistas();
        }
        if (menuItemRoles.isEnabled()) {
            vistaRoles = new ifrmRoles();
        }
        if (menuItemPermisos.isEnabled()) {
            vistaPermisos = new ifrmPermisos();
        }
        if (menuItemUsuarios.isEnabled()) {
            vistaUsuarios = new ifrmUsuarios();
        }
        if (btnVentas.isEnabled()) {
            vistaVentas = new ifrmVentas();
        }
        if (btnAyuda.isEnabled()) {
            VistaVentas2 = new ifrmVentas2();
        }
//        if (menuItemVentas.isEnabled()) {
//            vistaVentas = new ifrmVentas();
//        }
        if (menuItemInventario.isEnabled()) {
            vistaInventario = new ifrmInventario();
        }
        if (menuItemClientes.isEnabled()) {
            vistaClientes = new ifrmClientes();
        }
        if (menuItemNomina.isEnabled()) {
            vistaNomina = new ifrmNomina();
        }

    }//GEN-LAST:event_formWindowOpened

    private void menuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUsuariosActionPerformed

        mostrarVista(vistaUsuarios);
    }//GEN-LAST:event_menuItemUsuariosActionPerformed

    private void menuItemPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPermisosActionPerformed
        // TODO add your handling code here:
        mostrarVista(vistaPermisos);
    }//GEN-LAST:event_menuItemPermisosActionPerformed

    private void menuItemRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRolesActionPerformed
        // TODO add your handling code here:

        mostrarVista(vistaRoles);
    }//GEN-LAST:event_menuItemRolesActionPerformed

    private void menuItemVistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVistasActionPerformed
        // TODO add your handling code here:
        mostrarVista(vistaVistas);
    }//GEN-LAST:event_menuItemVistasActionPerformed

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        // Saliendo de la aplicacion
//
//        Conexion.getInstance().dispose();
//        System.exit(0);
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void menuItemNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNominaActionPerformed
        // TODO add your handling code here:

        //        panelCompras = new javax.swing.JPanel();
        //        panelMateriales = new javax.swing.JPanel();
        //        panelProveedores = new javax.swing.JPanel();
        //        panelSecciones = new javax.swing.JPanel();
        //        panelBodegas = new javax.swing.JPanel();
//        mostrarVista(vistaNomina);
    }//GEN-LAST:event_menuItemNominaActionPerformed

    private void menuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemClientesActionPerformed
//        mostrarVista(vistaClientes);
    }//GEN-LAST:event_menuItemClientesActionPerformed

    private void menuItemInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInventarioActionPerformed
        // TODO add your handling code here:

//        mostrarVista(vistaInventario);
    }//GEN-LAST:event_menuItemInventarioActionPerformed

    private void menuItemVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVentasActionPerformed
        // TODO add your handling code here:

      //  mostrarVista(vistaVentas);
    }//GEN-LAST:event_menuItemVentasActionPerformed

    private void menuArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuArchivoMouseClicked
        // TODO add your handling code here:
        mostrarVista(vistaVentas);
    }//GEN-LAST:event_menuArchivoMouseClicked

    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked
        // TODO add your handling code here:
        
        Conexion.getInstance().dispose();
        System.exit(0);
    }//GEN-LAST:event_jMenu9MouseClicked

    private void jMenu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu9ActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
         mostrarVista(vistaVentas);
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnVentasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnVentasMousePressed

    private void btnVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseClicked
        // TODO add your handling code here:
        mostrarVista(vistaVentas);
    }//GEN-LAST:event_btnVentasMouseClicked

    private void ClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientesMouseClicked
        // TODO add your handling code here:
        mostrarVista(vistaClientes);
    }//GEN-LAST:event_ClientesMouseClicked

    private void FacturacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacturacionMouseClicked
        // TODO add your handling code here:
        mostrarVista(vistaFacturas);
    }//GEN-LAST:event_FacturacionMouseClicked

    private void InventariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventariosMouseClicked
        // TODO add your handling code here:
        mostrarVista(vistaInventario);
    }//GEN-LAST:event_InventariosMouseClicked

    private void NominaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NominaMouseClicked
        // TODO add your handling code here:
        mostrarVista(vistaNomina);
    }//GEN-LAST:event_NominaMouseClicked

    private void VistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VistasMouseClicked
        // TODO add your handling code here:
        mostrarVista(vistaVistas);
    }//GEN-LAST:event_VistasMouseClicked

    private void RolesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RolesMouseClicked
        // TODO add your handling code here:
        mostrarVista(vistaRoles);
    }//GEN-LAST:event_RolesMouseClicked

    private void PermisosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PermisosMouseClicked
        // TODO add your handling code here:
        mostrarVista(vistaPermisos);
    }//GEN-LAST:event_PermisosMouseClicked

    private void EmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpleadosMouseClicked
        // TODO add your handling code here:
        mostrarVista(vistaUsuarios);
    }//GEN-LAST:event_EmpleadosMouseClicked

    private void btnAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAyudaMouseClicked
        // TODO add your handling code here:
        mostrarVista(VistaVentas2);
    }//GEN-LAST:event_btnAyudaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Clientes;
    private javax.swing.JMenu Config;
    private javax.swing.JMenu Empleados;
    private javax.swing.JMenu Facturacion;
    private javax.swing.JMenu Inventarios;
    private javax.swing.JMenu Nomina;
    private javax.swing.JMenu Permisos;
    private javax.swing.JMenu Proveedores;
    private javax.swing.JMenu Reportes;
    private javax.swing.JMenu Roles;
    private javax.swing.JMenu Vistas;
    private javax.swing.JMenuBar barraMenuPrincipal;
    private javax.swing.JMenu btnAyuda;
    private javax.swing.JMenu btnVentas;
    private javax.swing.JDesktopPane dpEscritorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenu menuAdministrar;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuItemClientes;
    private javax.swing.JMenuItem menuItemInventario;
    private javax.swing.JMenuItem menuItemNomina;
    private javax.swing.JMenuItem menuItemPermisos;
    private javax.swing.JMenuItem menuItemRoles;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JMenuItem menuItemUsuarios;
    private javax.swing.JMenuItem menuItemVentas;
    private javax.swing.JMenuItem menuItemVistas;
    private javax.swing.JMenu menuPreferencias;
    // End of variables declaration//GEN-END:variables
}
