/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zapateria.main.view;

/**
 *
 * @author Diego
 */
public class ifrmCambiarContrasena extends MarcoInternoPersonalizado {

    private static final long serialVersionUID = -5200719781220422290L;

    private long idUsuario = 0;

    /**
     * Creates new form ifrmCambiarContrasena
     *
     * @param idUsuario
     */
    public ifrmCambiarContrasena(long idUsuario) {
        initComponents();
        this.idUsuario = idUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCambiar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        passConfirmarContrasena = new javax.swing.JPasswordField();
        passContrasena = new javax.swing.JPasswordField();
        lbContrasena = new javax.swing.JLabel();
        lbConfirmarContrasena = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Cambiar contraseña");
        setMaximumSize(new java.awt.Dimension(392, 139));
        setMinimumSize(new java.awt.Dimension(392, 139));
        setPreferredSize(new java.awt.Dimension(392, 139));

        btnCambiar.setText("Cambiar");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        passConfirmarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passConfirmarContrasenaActionPerformed(evt);
            }
        });

        lbContrasena.setText("Contraseña nueva:");

        lbConfirmarContrasena.setText("Confirmar contraseña nueva:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCambiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbConfirmarContrasena)
                    .addComponent(lbContrasena))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passConfirmarContrasena)
                    .addComponent(passContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbContrasena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConfirmarContrasena)
                    .addComponent(passConfirmarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCambiar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        // TODO add your handling code here:

        String contrasena = String.copyValueOf(passContrasena.getPassword());
        String confirmarContrasena = String.copyValueOf(passConfirmarContrasena.getPassword());

        if (contrasena.length() > 2 && confirmarContrasena.length() > 2) {
            if (contrasena.equals(confirmarContrasena)) {
                if (servicio.cambiarContrasena(idUsuario, contrasena)) {
                    mostrarMensaje("Se ha cambiado la contraseña satisfactoriamente");
                    this.dispose();
                } else {
                    mostrarMensaje("No se pudo cambiar la contraseña");
                }
            } else {
                mostrarMensaje("Las constraseñas no coinciden");
            }
        } else {
            mostrarMensaje("Escriba una contraseña mas larga");
        }
    }//GEN-LAST:event_btnCambiarActionPerformed

    private void passConfirmarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passConfirmarContrasenaActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_passConfirmarContrasenaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cerrar();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lbConfirmarContrasena;
    private javax.swing.JLabel lbContrasena;
    private javax.swing.JPasswordField passConfirmarContrasena;
    private javax.swing.JPasswordField passContrasena;
    // End of variables declaration//GEN-END:variables
}
