/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zapateria.main.view;

import com.zapateria.main.dto.SesionDTO;
import com.zapateria.main.dto.UsuarioDTO;
import com.zapateria.main.util.BuscadorCarpeta;
import com.zapateria.main.util.Conexion;
import com.zapateria.main.util.Sesion;
import static groovy.xml.Entity.amp;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Usuario
 */
public class Escritorio extends MarcoPersonalizado {

    private static final long serialVersionUID = 5947777371087563681L;

    private static final String VISTAS = "VISTAS", ROLES = "ROLES",
            PERMISOS = "PERMISOS", USUARIOS = "USUARIOS", VENTAS = "VENTAS", CLIENTES = "CLIENTES",
            INVENTARIO = "INVENTARIO", NOMINA = "NOMINA", VENTAS2 = "VENTAS2", FACTURACION = "FACTURACION", REPORTES = "REPORTES", LOGIN = "LOGIN", AUXILIAR = "AUXILIAR", ABOUT = "ABOUT";

    private static SesionDTO SESION_USUARIO = Sesion.obtenerSesion();

    private ifrmInventario vistaInventario;
    private ifrmNomina vistaNomina;
    private ifrmClientes vistaClientes;
    private ifrmPermisos vistaPermisos;
    private ifrmRoles vistaRoles;
    private ifrmUsuarios vistaUsuarios;
    private ifrmVentas3 vistaVentas;
    private ifrmVistas vistaVistas;
    private ifrmFactura vistaFacturas;
    private ifrmVentas2 VistaVentas2;
    private ifrmReportes vistaReportes;
    private frmLogin vistaLogin;
    private ifrmLibroAux vistaLibro;
    private ConfirmarUsuario confirmar;
    private About about;
    

    /**
     * Creates new form Escritorio
     */
    public Escritorio() {
        initComponents2();
        String CARPETA = "db";
        BuscadorCarpeta b = null;
        String c = b.buscar(CARPETA);
        ImageIcon ImageIcon = new ImageIcon(c + "//icon2.png");
        Image Image = ImageIcon.getImage();
        this.setIconImage(Image);
        this.setTitle("Contabilidad");
        this.menuArchivo.setVisible(false);
      // this.dpEscritorio.setBorder(new ImagenFondo());
        this.menuPreferencias.setVisible(false);
        setDefaultCloseOperation(0);
//        btnAbout.setVisible(true);

//      this.setIconImage(new ImageIcon(getClass().getResource(".../com.zapateria.main.imagenes/icon.png")).getImage());
    }

//    @Override
//        public Image getIconImage() {
//        Image retValue = Toolkit.getDefaultToolkit().
//                getImage(ClassLoader.getSystemResource("src\\com\\zapateria\\main\\images\\icon.png"));
//
//
//        return retValue;
//    }
    public void mostrarVista(JInternalFrame ifrm) {

        if (ifrm != null && !ifrm.isShowing()) {
            dpEscritorio.add(ifrm);
            //centra el JinternalFrame
            Dimension desktopSize = dpEscritorio.getSize();
            Dimension FrameSize = ifrm.getSize();
            ifrm.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            //Abre Maximizado el JinternalFrame
            try {
                ifrm.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(ifrmVentas.class.getName()).log(Level.SEVERE, null, ex);
            }

            //ifrm.setLayout(null);
            ifrm.show();
        } else if (ifrm == null) {
            mostrarMensaje("Usted no tiene permiso para ingresar aqui");
        }
    }

    public void crearAbonoPrestamo() {
        ArrayList<UsuarioDTO> list = servicio.listarUsuarios();
        for (UsuarioDTO u : list) {
            long id = u.getId();
            servicio.crearAbonoUsuario(id, 0, 0, 0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpEscritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        barraMenuPrincipal = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuItemVentas = new javax.swing.JMenuItem();
        menuItemInventario = new javax.swing.JMenuItem();
        menuItemClientes = new javax.swing.JMenuItem();
        menuItemNomina = new javax.swing.JMenuItem();
        menuItemSalir = new javax.swing.JMenuItem();
        menuPreferencias = new javax.swing.JMenu();
        menuAdministrar = new javax.swing.JMenu();
        menuItemVistas = new javax.swing.JMenuItem();
        menuItemRoles = new javax.swing.JMenuItem();
        menuItemPermisos = new javax.swing.JMenuItem();
        menuItemUsuarios = new javax.swing.JMenuItem();
        btnVentas = new javax.swing.JMenu();
        btnFacturacion = new javax.swing.JMenu();
        btnReportes = new javax.swing.JMenu();
        Clientes = new javax.swing.JMenu();
        Empleados = new javax.swing.JMenu();
        Nomina = new javax.swing.JMenu();
        Inventarios = new javax.swing.JMenu();
        Roles = new javax.swing.JMenu();
        Vistas = new javax.swing.JMenu();
        btnLibroAux = new javax.swing.JMenu();
        Permisos = new javax.swing.JMenu();
        btnLimpiarBase = new javax.swing.JMenu();
        btnCrearBase = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        btnAbout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zapateria");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        dpEscritorio.setBackground(new java.awt.Color(255, 255, 255));
        dpEscritorio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dpEscritorio.setToolTipText("Escritorio");
        dpEscritorio.setDoubleBuffered(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/fondo.jpg"))); // NOI18N
        jLabel1.setOpaque(true);

        dpEscritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpEscritorioLayout = new javax.swing.GroupLayout(dpEscritorio);
        dpEscritorio.setLayout(dpEscritorioLayout);
        dpEscritorioLayout.setHorizontalGroup(
            dpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpEscritorioLayout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jLabel1)
                .addContainerGap(612, Short.MAX_VALUE))
        );
        dpEscritorioLayout.setVerticalGroup(
            dpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpEscritorioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        barraMenuPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/ventas.png"))); // NOI18N
        menuArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuArchivoMouseClicked(evt);
            }
        });

        menuItemVentas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        menuItemVentas.setText("Ventas");
        menuItemVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVentasActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemVentas);

        menuItemInventario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        menuItemInventario.setText("Inventario");
        menuItemInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInventarioActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemInventario);

        menuItemClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menuItemClientes.setText("Clientes");
        menuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemClientesActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemClientes);

        menuItemNomina.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        menuItemNomina.setText("Nómina");
        menuItemNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNominaActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemNomina);

        menuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemSalir);

        barraMenuPrincipal.add(menuArchivo);

        menuPreferencias.setText("Preferencias");

        menuAdministrar.setText("Administrar");

        menuItemVistas.setText("Ventanas y pestañas");
        menuItemVistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVistasActionPerformed(evt);
            }
        });
        menuAdministrar.add(menuItemVistas);

        menuItemRoles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuItemRoles.setText("Roles");
        menuItemRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRolesActionPerformed(evt);
            }
        });
        menuAdministrar.add(menuItemRoles);

        menuItemPermisos.setText("Permisos");
        menuItemPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPermisosActionPerformed(evt);
            }
        });
        menuAdministrar.add(menuItemPermisos);

        menuItemUsuarios.setText("Usuarios");
        menuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUsuariosActionPerformed(evt);
            }
        });
        menuAdministrar.add(menuItemUsuarios);

        menuPreferencias.add(menuAdministrar);

        barraMenuPrincipal.add(menuPreferencias);

        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/VENTAS.png"))); // NOI18N
        btnVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentasMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVentasMousePressed(evt);
            }
        });
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        barraMenuPrincipal.add(btnVentas);

        btnFacturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/FACTURACION.png"))); // NOI18N
        btnFacturacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFacturacionMouseClicked(evt);
            }
        });
        barraMenuPrincipal.add(btnFacturacion);

        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/REPORTES.png"))); // NOI18N
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportesMouseClicked(evt);
            }
        });
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        barraMenuPrincipal.add(btnReportes);

        Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/CLIENTES.png"))); // NOI18N
        Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientesMouseClicked(evt);
            }
        });
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        barraMenuPrincipal.add(Clientes);

        Empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/EMPLEADOS.png"))); // NOI18N
        Empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpleadosMouseClicked(evt);
            }
        });
        Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadosActionPerformed(evt);
            }
        });
        barraMenuPrincipal.add(Empleados);

        Nomina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/NOMINA.png"))); // NOI18N
        Nomina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NominaMouseClicked(evt);
            }
        });
        barraMenuPrincipal.add(Nomina);

        Inventarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/INVENTARIOS.png"))); // NOI18N
        Inventarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventariosMouseClicked(evt);
            }
        });
        barraMenuPrincipal.add(Inventarios);

        Roles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/ROLES.png"))); // NOI18N
        Roles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RolesMouseClicked(evt);
            }
        });
        barraMenuPrincipal.add(Roles);

        Vistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/VISTAS.png"))); // NOI18N
        Vistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VistasMouseClicked(evt);
            }
        });
        barraMenuPrincipal.add(Vistas);

        btnLibroAux.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/unnamed_opt.png"))); // NOI18N
        btnLibroAux.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLibroAuxMouseClicked(evt);
            }
        });
        btnLibroAux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibroAuxActionPerformed(evt);
            }
        });
        barraMenuPrincipal.add(btnLibroAux);

        Permisos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/PERMISOS.png"))); // NOI18N
        Permisos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PermisosMouseClicked(evt);
            }
        });
        barraMenuPrincipal.add(Permisos);

        btnLimpiarBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/limpi2.png"))); // NOI18N
        btnLimpiarBase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarBaseMouseClicked(evt);
            }
        });
        btnLimpiarBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarBaseActionPerformed(evt);
            }
        });
        barraMenuPrincipal.add(btnLimpiarBase);

        btnCrearBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/Bases3.png"))); // NOI18N
        btnCrearBase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearBaseMouseClicked(evt);
            }
        });
        btnCrearBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearBaseActionPerformed(evt);
            }
        });
        barraMenuPrincipal.add(btnCrearBase);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/SALIR.png"))); // NOI18N
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        jMenu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu9ActionPerformed(evt);
            }
        });
        barraMenuPrincipal.add(jMenu9);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/SALIR.png"))); // NOI18N
        jMenu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu10MouseClicked(evt);
            }
        });
        jMenu10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu10ActionPerformed(evt);
            }
        });
        barraMenuPrincipal.add(jMenu10);

        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/SWT_opt.png"))); // NOI18N
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutMouseClicked(evt);
            }
        });
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        barraMenuPrincipal.add(btnAbout);

        setJMenuBar(barraMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpEscritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dpEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initComponents2() {

        dpEscritorio = new javax.swing.JDesktopPane();
        barraMenuPrincipal = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();

        menuItemVentas = new javax.swing.JMenuItem();
        menuItemInventario = new javax.swing.JMenuItem();
        menuItemClientes = new javax.swing.JMenuItem();
        menuItemNomina = new javax.swing.JMenuItem();
        btnLibroAux = new javax.swing.JMenu();
        menuItemSalir = new javax.swing.JMenuItem();
        menuPreferencias = new javax.swing.JMenu();
        menuAdministrar = new javax.swing.JMenu();
        menuItemVistas = new javax.swing.JMenuItem();
        menuItemRoles = new javax.swing.JMenuItem();
        menuItemPermisos = new javax.swing.JMenuItem();
        menuItemUsuarios = new javax.swing.JMenuItem();
        btnVentas = new javax.swing.JMenu();
        Clientes = new javax.swing.JMenu();
        btnFacturacion = new javax.swing.JMenu();
        btnReportes = new javax.swing.JMenu();
        Empleados = new javax.swing.JMenu();
        Nomina = new javax.swing.JMenu();
        Inventarios = new javax.swing.JMenu();
        Roles = new javax.swing.JMenu();
        Permisos = new javax.swing.JMenu();
        Vistas = new javax.swing.JMenu();
        btnAbout = new javax.swing.JMenu();
        btnCrearBase = new javax.swing.JMenu();
        btnLimpiarBase = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zapateria");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        dpEscritorio.setBackground(new java.awt.Color(255, 255, 255));
        dpEscritorio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dpEscritorio.setToolTipText("Escritorio");
        dpEscritorio.setDoubleBuffered(true);

        javax.swing.GroupLayout dpEscritorioLayout = new javax.swing.GroupLayout(dpEscritorio);
        dpEscritorio.setLayout(dpEscritorioLayout);
        dpEscritorioLayout.setHorizontalGroup(
                dpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1548, Short.MAX_VALUE)
        );
        dpEscritorioLayout.setVerticalGroup(
                dpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 373, Short.MAX_VALUE)
        );

        barraMenuPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/VENTAS.png"))); // NOI18N
        menuArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuArchivoMouseClicked(evt);
            }
        });

        menuItemVentas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        menuItemVentas.setText("Ventas");
        menuItemVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVentasActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemVentas);

        menuItemInventario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        menuItemInventario.setText("Inventario");
        menuItemInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInventarioActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemInventario);

        menuItemClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menuItemClientes.setText("Clientes");
        menuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemClientesActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemClientes);

        menuItemNomina.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        menuItemNomina.setText("Nómina");
        menuItemNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNominaActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemNomina);

        menuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemSalir);

        barraMenuPrincipal.add(menuArchivo);

        menuPreferencias.setText("Preferencias");

        menuAdministrar.setText("Administrar");

        menuItemVistas.setText("Ventanas y pestañas");
        menuItemVistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVistasActionPerformed(evt);
            }
        });
        menuAdministrar.add(menuItemVistas);

        menuItemRoles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuItemRoles.setText("Roles");
        menuItemRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRolesActionPerformed(evt);
            }
        });
        menuAdministrar.add(menuItemRoles);

        menuItemPermisos.setText("Permisos");
        menuItemPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPermisosActionPerformed(evt);
            }
        });
        menuAdministrar.add(menuItemPermisos);

        menuItemUsuarios.setText("Usuarios");
        menuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUsuariosActionPerformed(evt);
            }
        });
        menuAdministrar.add(menuItemUsuarios);

        menuPreferencias.add(menuAdministrar);

        barraMenuPrincipal.add(menuPreferencias);

        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/VENTAS.png"))); // NOI18N
        btnVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentasMouseClicked(evt);
            }

            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVentasMousePressed(evt);
            }
        });
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        barraMenuPrincipal.add(btnVentas);

        btnFacturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/FACTURACION.png"))); // NOI18N
        btnFacturacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFacturacionMouseClicked(evt);
            }
        });
        barraMenuPrincipal.add(btnFacturacion);

        btnLibroAux.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/unnamed_opt.png"))); // NOI18N
        btnLibroAux.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLibroAuxMouseClicked(evt);
            }
        });

        barraMenuPrincipal.add(btnLibroAux);

        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/REPORTES.png"))); // NOI18N
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportesMouseClicked(evt);
            }
        });
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        barraMenuPrincipal.add(btnReportes);

        Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/CLIENTES.png"))); // NOI18N
        Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientesMouseClicked(evt);
            }
        });
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        barraMenuPrincipal.add(Clientes);

        Empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/EMPLEADOS.png"))); // NOI18N
        Empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpleadosMouseClicked(evt);
            }
        });
        Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadosActionPerformed(evt);
            }
        });
        barraMenuPrincipal.add(Empleados);

        Nomina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/NOMINA.png"))); // NOI18N
        Nomina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NominaMouseClicked(evt);
            }
        });
        barraMenuPrincipal.add(Nomina);

        Inventarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/INVENTARIOS.png"))); // NOI18N
        Inventarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventariosMouseClicked(evt);
            }
        });
        barraMenuPrincipal.add(Inventarios);

        Roles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/ROLES.png"))); // NOI18N
        Roles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RolesMouseClicked(evt);
            }
        });
        barraMenuPrincipal.add(Roles);

        Permisos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/PERMISOS.png"))); // NOI18N
        Permisos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PermisosMouseClicked(evt);
            }
        });
        barraMenuPrincipal.add(Permisos);

        Vistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/VISTAS.png"))); // NOI18N
        Vistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VistasMouseClicked(evt);
            }
        });
        barraMenuPrincipal.add(Vistas);

        btnCrearBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/Bases3.png"))); // NOI18N
        btnCrearBase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearBaseMouseClicked(evt);
            }
        });

        barraMenuPrincipal.add(btnCrearBase);

        btnLimpiarBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/limpi2.png"))); // NOI18N
        btnLimpiarBase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarBaseMouseClicked(evt);
            }
        });
        btnLimpiarBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarBaseActionPerformed(evt);
            }
        });
        barraMenuPrincipal.add(btnLimpiarBase);
        
        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/SWT_opt.png"))); // NOI18N
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutMouseClicked(evt);
            }
        });
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        barraMenuPrincipal.add(btnAbout);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/SALIR.png"))); // NOI18N
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        jMenu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu9ActionPerformed(evt);
            }
        });
        barraMenuPrincipal.add(jMenu9);

        setJMenuBar(barraMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(dpEscritorio)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dpEscritorio)
        );

        pack();
    }// </editor-fold>               
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        // Aplicando los permisos disponibles para el usuario que inició la sesión.
        menuItemVistas.setEnabled(SESION_USUARIO.isVistaPermitida(VISTAS));
        menuItemRoles.setEnabled(SESION_USUARIO.isVistaPermitida(ROLES));
        menuItemPermisos.setEnabled(SESION_USUARIO.isVistaPermitida(PERMISOS));
        menuItemUsuarios.setEnabled(SESION_USUARIO.isVistaPermitida(USUARIOS));
        //menuItemVentas.setEnabled(SESION_USUARIO.isVistaPermitida(VENTAS));
        menuItemInventario.setEnabled(SESION_USUARIO.isVistaPermitida(INVENTARIO));
        menuItemClientes.setEnabled(SESION_USUARIO.isVistaPermitida(CLIENTES));
        menuItemNomina.setEnabled(SESION_USUARIO.isVistaPermitida(NOMINA));
        btnReportes.setEnabled(SESION_USUARIO.isVistaPermitida(REPORTES));
//        btnAbout.setEnabled(SESION_USUARIO.isVistaPermitida(REPORTES));
        btnVentas.setEnabled(SESION_USUARIO.isVistaPermitida(VENTAS));

        //jMenu9.setEnabled(SESION_USUARIO.isVistaPermitida(LOGIN));
        // btnFacturacion.setEnabled(SESION_USUARIO.isVistaPermitida(FACTURACION));
        //Instanciando las vistas si el menu que las activa esta habilitado
       
     
        
        
        if (menuItemUsuarios.isEnabled()) {
            vistaUsuarios = new ifrmUsuarios();
            vistaUsuarios.setSize(dpEscritorio.getWidth(), dpEscritorio.getHeight());
        }
        if (btnAbout.isEnabled()) {
            about = new About();
            about.setSize(dpEscritorio.getWidth(), dpEscritorio.getHeight());
        }
       

      

        if (jMenu9.isEnabled()) {
            vistaLogin = new frmLogin();
            vistaLogin.setSize(dpEscritorio.getWidth(), dpEscritorio.getHeight());

        }

       

//        if (menuItemVentas.isEnabled()) {
//            vistaVentas = new ifrmVentas();
//        }
        
//        if (menuItemClientes.isEnabled()) {
//            vistaClientes = new ifrmClientes();
//            vistaClientes.setSize(dpEscritorio.getWidth(), dpEscritorio.getHeight());
//        }
      

      


    }//GEN-LAST:event_formWindowOpened

    private void menuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUsuariosActionPerformed
        if (!vistaUsuarios.isVisible()) {
            mostrarVista(vistaUsuarios);
        } else {
            vistaUsuarios.cerrar();
            mostrarVista(vistaUsuarios);
        }
    }//GEN-LAST:event_menuItemUsuariosActionPerformed

    private void menuItemPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPermisosActionPerformed
        // TODO add your handling code here:
        if (!vistaPermisos.isVisible()) {
            mostrarVista(vistaPermisos);
        } else {
            vistaPermisos.cerrar();
            mostrarVista(vistaPermisos);
        }
    }//GEN-LAST:event_menuItemPermisosActionPerformed

    private void menuItemRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRolesActionPerformed
        // TODO add your handling code here:
        if (!vistaRoles.isVisible()) {
            mostrarVista(vistaRoles);
        } else {
            vistaRoles.cerrar();
            mostrarVista(vistaRoles);
        }
    }//GEN-LAST:event_menuItemRolesActionPerformed

    private void menuItemVistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVistasActionPerformed
        // TODO add your handling code here:
        if (!vistaVistas.isVisible()) {
            mostrarVista(vistaVistas);
        } else {
            vistaVistas.cerrar();
            mostrarVista(vistaVistas);
        }
    }//GEN-LAST:event_menuItemVistasActionPerformed

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        // Saliendo de la aplicacion
//
//        Conexion.getInstance().dispose();
//        System.exit(0);
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void menuItemNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNominaActionPerformed
        // TODO add your handling code here:

        //        panelCompras = new javax.swing.JPanel();
        //        panelMateriales = new javax.swing.JPanel();
        //        panelProveedores = new javax.swing.JPanel();
        //        panelSecciones = new javax.swing.JPanel();
        //        panelBodegas = new javax.swing.JPanel();
//        mostrarVista(vistaNomina);
    }//GEN-LAST:event_menuItemNominaActionPerformed

    private void menuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemClientesActionPerformed
//        mostrarVista(vistaClientes);
    }//GEN-LAST:event_menuItemClientesActionPerformed

    private void menuItemInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInventarioActionPerformed
        // TODO add your handling code here:

//        mostrarVista(vistaInventario);
    }//GEN-LAST:event_menuItemInventarioActionPerformed

    private void menuItemVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVentasActionPerformed
        // TODO add your handling code here:

        //  mostrarVista(vistaVentas);
    }//GEN-LAST:event_menuItemVentasActionPerformed

    private void menuArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuArchivoMouseClicked
        // TODO add your handling code here:
        if (!vistaVentas.isVisible()) {
            mostrarVista(vistaVentas);
        } else {
            vistaVentas.cerrar();
            mostrarVista(vistaVentas);
        }
    }//GEN-LAST:event_menuArchivoMouseClicked

    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked
       

        System.exit(0);
    }//GEN-LAST:event_jMenu9MouseClicked

    private void jMenu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu9ActionPerformed

    }//GEN-LAST:event_jMenu9ActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
        if (!vistaVentas.isVisible()) {
            mostrarVista(vistaVentas);
        } else {
            vistaVentas.cerrar();
            mostrarVista(vistaVentas);
        }
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnVentasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnVentasMousePressed

    private void btnVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseClicked
        // TODO add your handling code here:
         if (btnVentas.isEnabled()) {
            vistaVentas = new ifrmVentas3();
            vistaUsuarios.setSize(dpEscritorio.getWidth(), dpEscritorio.getHeight());
        }
        if (!vistaVentas.isVisible()) {
            mostrarVista(vistaVentas);
        } else {
            vistaVentas.cerrar();
            mostrarVista(vistaVentas);
        }
    }//GEN-LAST:event_btnVentasMouseClicked


    private void ClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientesMouseClicked
        // TODO add your handling code here:
if (menuItemClientes.isEnabled()) {
            vistaClientes = new ifrmClientes();
            vistaClientes.setSize(dpEscritorio.getWidth(), dpEscritorio.getHeight());
        }
        
        if (!vistaClientes.isVisible()) {
            mostrarVista(vistaClientes);

        } else {
            vistaClientes.cerrar();
            mostrarVista(vistaClientes);
        }
    }//GEN-LAST:event_ClientesMouseClicked

    private void btnFacturacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturacionMouseClicked
        // TODO add your handling code here:
         if (btnFacturacion.isEnabled()) {
            vistaFacturas = new ifrmFactura();
            vistaFacturas.setSize(dpEscritorio.getWidth(), dpEscritorio.getHeight());
        }
        if (!vistaFacturas.isVisible()) {
            mostrarVista(vistaFacturas);
        } else {
            vistaFacturas.cerrar();
            mostrarVista(vistaFacturas);
        }

    }//GEN-LAST:event_btnFacturacionMouseClicked

    private void InventariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventariosMouseClicked
        // TODO add your handling code here:
        if (menuItemInventario.isEnabled()) {
            vistaInventario = new ifrmInventario();
            vistaInventario.setSize(dpEscritorio.getWidth(), dpEscritorio.getHeight());
        }
        if (!vistaInventario.isVisible()) {
            mostrarVista(vistaInventario);
        } else {
            vistaInventario.cerrar();
            mostrarVista(vistaInventario);
        }
    }//GEN-LAST:event_InventariosMouseClicked

    private void NominaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NominaMouseClicked
        // TODO add your handling code here:
          if (menuItemNomina.isEnabled()) {
            vistaNomina = new ifrmNomina();
            vistaNomina.setSize(dpEscritorio.getWidth(), dpEscritorio.getHeight());
        }
        if (!vistaNomina.isVisible()) {
            mostrarVista(vistaNomina);
        } else {
            vistaNomina.cerrar();
            mostrarVista(vistaNomina);
        }

    }//GEN-LAST:event_NominaMouseClicked

    private void VistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VistasMouseClicked
        // TODO add your handling code here:
           if (menuItemVistas.isEnabled()) {
            vistaVistas = new ifrmVistas();
            vistaVistas.setSize(dpEscritorio.getWidth(), dpEscritorio.getHeight());
        }
        if (!vistaVistas.isVisible()) {
            mostrarVista(vistaVistas);
        } else {
            vistaVistas.cerrar();
            mostrarVista(vistaVistas);
        }
    }//GEN-LAST:event_VistasMouseClicked

    private void RolesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RolesMouseClicked
        // TODO add your handling code here:
        if (menuItemRoles.isEnabled()) {
            vistaRoles = new ifrmRoles();
            vistaRoles.setSize(dpEscritorio.getWidth(), dpEscritorio.getHeight());
        }
        if (!vistaRoles.isVisible()) {
            mostrarVista(vistaRoles);
        } else {
            vistaRoles.cerrar();
            mostrarVista(vistaRoles);
        }
    }//GEN-LAST:event_RolesMouseClicked

    private void PermisosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PermisosMouseClicked
        // TODO add your handling code here:
        if (menuItemPermisos.isEnabled()) {
            vistaPermisos = new ifrmPermisos();
            vistaPermisos.setSize(dpEscritorio.getWidth(), dpEscritorio.getHeight());
        }
        if (!vistaPermisos.isVisible()) {
            mostrarVista(vistaPermisos);
        } else {
            vistaPermisos.cerrar();
            mostrarVista(vistaPermisos);
        }
    }//GEN-LAST:event_PermisosMouseClicked

    private void EmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpleadosMouseClicked
        // TODO add your handling code here:
        if (!vistaUsuarios.isVisible()) {
            mostrarVista(vistaUsuarios);
        } else {
            vistaUsuarios.cerrar();
            mostrarVista(vistaUsuarios);
        }
    }//GEN-LAST:event_EmpleadosMouseClicked

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientesActionPerformed

    private void EmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpleadosActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed


    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseClicked
         if (btnReportes.isEnabled()) {
            vistaReportes = new ifrmReportes();
            vistaReportes.setSize(dpEscritorio.getWidth(), dpEscritorio.getHeight());

        }
        if (!vistaReportes.isVisible()) {
            mostrarVista(vistaReportes);
        } else {
            vistaReportes.cerrar();
            mostrarVista(vistaReportes);
        }
    }//GEN-LAST:event_btnReportesMouseClicked

    private void btnCrearBaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearBaseMouseClicked
        boolean x = servicio.crearSQL();
        if (x) {
            // mostrarMensaje("Se genero la copia con exito");
        } else {
            mostrarMensaje("No se genero la copia");
        }
    }//GEN-LAST:event_btnCrearBaseMouseClicked

    private void btnCrearBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearBaseActionPerformed

    }//GEN-LAST:event_btnCrearBaseActionPerformed

    private void btnLimpiarBaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarBaseMouseClicked
//         servicio.crearSQL();
//        boolean x = servicio.LimpiarBase();
//        boolean y = servicio.LimpiarAbonoUsuario();
//        boolean z = servicio.LimpiarFactura();
//        boolean a = servicio.LimpiarLiquidacion();
//        boolean b = servicio.LimpiarNominaUsuario();
//        boolean c = servicio.LimpiarPrestamoUsuario();
//        if (c) {
//
//            mostrarMensaje("La base de datos se ha limpiado");
//        } else {
//            mostrarMensaje("La base de datos  se ha limpiado");
//        }
        // crearAbonoPrestamo();
        
          if (btnLimpiarBase.isEnabled()) {
            confirmar = new ConfirmarUsuario();
            confirmar.setSize(dpEscritorio.getWidth(), dpEscritorio.getHeight());
        }

        if (!confirmar.isVisible()) {
            mostrarVista(confirmar);
        } else {
            confirmar.cerrar();
            mostrarVista(confirmar);
        }
//        this.add(Confirmar);
//        Confirmar.setVisible(true);
//        Confirmar.setSize(392, 139);
    }//GEN-LAST:event_btnLimpiarBaseMouseClicked

    private void btnLimpiarBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarBaseActionPerformed
        boolean x = servicio.LimpiarBase();
        boolean y = servicio.LimpiarAbonoUsuario();
        boolean z = servicio.LimpiarFactura();
        boolean a = servicio.LimpiarLiquidacion();
        boolean b = servicio.LimpiarNominaUsuario();
        boolean c = servicio.LimpiarPrestamoUsuario();
        if (c) {

            mostrarMensaje("La base de datos se ha limpiado");
        } else {
            mostrarMensaje("La base de datos  se ha limpiado");
        }
        crearAbonoPrestamo();
    }//GEN-LAST:event_btnLimpiarBaseActionPerformed

    private void btnLibroAuxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibroAuxMouseClicked
         if (btnLibroAux.isEnabled()) {
            vistaLibro = new ifrmLibroAux();
            vistaLibro.setSize(dpEscritorio.getWidth(), dpEscritorio.getHeight());

        }
        if (!vistaLibro.isVisible()) {
            mostrarVista(vistaLibro);
        } else {
            vistaLibro.cerrar();
            mostrarVista(vistaLibro);
        }
    }//GEN-LAST:event_btnLibroAuxMouseClicked

    private void btnLibroAuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibroAuxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLibroAuxActionPerformed

    private void btnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseClicked
        if (!about.isVisible()) {
            mostrarVista(about);
            
            about.setSize(450, 400);
            about.setLocation(400,100);
        } else {
            about.cerrar();
            mostrarVista(about);
        }
    }//GEN-LAST:event_btnAboutMouseClicked

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAboutActionPerformed

    private void jMenu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu10MouseClicked

    private void jMenu10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu10ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Clientes;
    private javax.swing.JMenu Empleados;
    private javax.swing.JMenu Inventarios;
    private javax.swing.JMenu Nomina;
    private javax.swing.JMenu Permisos;
    private javax.swing.JMenu Roles;
    private javax.swing.JMenu Vistas;
    private javax.swing.JMenuBar barraMenuPrincipal;
    private javax.swing.JMenu btnAbout;
    private javax.swing.JMenu btnCrearBase;
    private javax.swing.JMenu btnFacturacion;
    private javax.swing.JMenu btnLibroAux;
    private javax.swing.JMenu btnLimpiarBase;
    private javax.swing.JMenu btnReportes;
    private javax.swing.JMenu btnVentas;
    private javax.swing.JDesktopPane dpEscritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenu menuAdministrar;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuItemClientes;
    private javax.swing.JMenuItem menuItemInventario;
    private javax.swing.JMenuItem menuItemNomina;
    private javax.swing.JMenuItem menuItemPermisos;
    private javax.swing.JMenuItem menuItemRoles;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JMenuItem menuItemUsuarios;
    private javax.swing.JMenuItem menuItemVentas;
    private javax.swing.JMenuItem menuItemVistas;
    private javax.swing.JMenu menuPreferencias;
    // End of variables declaration//GEN-END:variables

}
