/*,
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zapateria.main.view;

import com.zapateria.main.dto.RolDTO;
import com.zapateria.main.dto.UsuarioDTO;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class ifrmRegistrarUsuario extends MarcoInternoPersonalizado {

    private static final long serialVersionUID = 7028967453495976775L;

    private final ifrmUsuarios vistaUsuarios;

    /**
     * Creates new form RegistrarUsuario
     *
     *
     * @param vistaUsuarios
     */
    public ifrmRegistrarUsuario(ifrmUsuarios vistaUsuarios) {
        this.vistaUsuarios = vistaUsuarios;
        initComponents();
        lbNombreUsuario.setVisible(false);
            lbContrasena.setVisible(false);
            lbConfirmarContrasena.setVisible(false);
            textNombreUsuario.setVisible(false);
            passContrasena.setVisible(false);
            passConfirmarContrasena.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatosUsuario = new javax.swing.JPanel();
        lbNombreUsuario = new javax.swing.JLabel();
        lbContrasena = new javax.swing.JLabel();
        lbConfirmarContrasena = new javax.swing.JLabel();
        textNombreUsuario = new javax.swing.JTextField();
        passContrasena = new javax.swing.JPasswordField();
        passConfirmarContrasena = new javax.swing.JPasswordField();
        comboRoles = new javax.swing.JComboBox<>();
        lbRol = new javax.swing.JLabel();
        panelDatosPersonales = new javax.swing.JPanel();
        lbDocumento1 = new javax.swing.JLabel();
        lbApellidos1 = new javax.swing.JLabel();
        lbNombres1 = new javax.swing.JLabel();
        textNombres = new javax.swing.JTextField();
        textApellidos = new javax.swing.JTextField();
        textDocumento = new javax.swing.JTextField();
        ckUsuario = new javax.swing.JCheckBox();
        textTelefono = new javax.swing.JTextField();
        lbDocumento2 = new javax.swing.JLabel();
        textDireccion = new javax.swing.JTextField();
        lbDocumento3 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Registrar usuario nuevo");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/icon2.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(391, 355));
        setMinimumSize(new java.awt.Dimension(391, 355));
        setName("Registrar usuario nuevo"); // NOI18N
        setPreferredSize(new java.awt.Dimension(391, 355));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        panelDatosUsuario.setBackground(new java.awt.Color(255, 255, 255));
        panelDatosUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del usuario"));

        lbNombreUsuario.setText("Nombre de usuario:");
        lbNombreUsuario.setToolTipText("");

        lbContrasena.setText("Contraseña:");
        lbContrasena.setToolTipText("");

        lbConfirmarContrasena.setText("Confirmar contraseña:");
        lbConfirmarContrasena.setToolTipText("");

        textNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreUsuarioActionPerformed(evt);
            }
        });

        comboRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un rol" }));
        comboRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRolesActionPerformed(evt);
            }
        });

        lbRol.setText("Rol:");
        lbRol.setToolTipText("");

        javax.swing.GroupLayout panelDatosUsuarioLayout = new javax.swing.GroupLayout(panelDatosUsuario);
        panelDatosUsuario.setLayout(panelDatosUsuarioLayout);
        panelDatosUsuarioLayout.setHorizontalGroup(
            panelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosUsuarioLayout.createSequentialGroup()
                        .addGroup(panelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbConfirmarContrasena)
                            .addComponent(lbNombreUsuario)
                            .addComponent(lbContrasena))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(passContrasena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(passConfirmarContrasena)
                            .addComponent(textNombreUsuario, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosUsuarioLayout.createSequentialGroup()
                        .addComponent(lbRol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboRoles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))))
        );
        panelDatosUsuarioLayout.setVerticalGroup(
            panelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosUsuarioLayout.createSequentialGroup()
                .addGroup(panelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRol)
                    .addComponent(comboRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(panelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreUsuario)
                    .addComponent(textNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbContrasena)
                    .addComponent(passContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConfirmarContrasena)
                    .addComponent(passConfirmarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelDatosPersonales.setBackground(new java.awt.Color(255, 255, 255));
        panelDatosPersonales.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos personales"));

        lbDocumento1.setText("Documento:");
        lbDocumento1.setToolTipText("");

        lbApellidos1.setText("Apellidos:");

        lbNombres1.setText("Nombres:");

        textNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombresActionPerformed(evt);
            }
        });

        textApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textApellidosActionPerformed(evt);
            }
        });

        textDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDocumentoActionPerformed(evt);
            }
        });

        ckUsuario.setBackground(new java.awt.Color(255, 255, 255));
        ckUsuario.setText("Usuario");
        ckUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckUsuarioActionPerformed(evt);
            }
        });

        textTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTelefonoActionPerformed(evt);
            }
        });

        lbDocumento2.setText("Telefono");
        lbDocumento2.setToolTipText("");

        textDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDireccionActionPerformed(evt);
            }
        });

        lbDocumento3.setText("Direccion");
        lbDocumento3.setToolTipText("");

        javax.swing.GroupLayout panelDatosPersonalesLayout = new javax.swing.GroupLayout(panelDatosPersonales);
        panelDatosPersonales.setLayout(panelDatosPersonalesLayout);
        panelDatosPersonalesLayout.setHorizontalGroup(
            panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDatosPersonalesLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lbApellidos1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textApellidos))
                    .addGroup(panelDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbDocumento1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosPersonalesLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lbNombres1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelDatosPersonalesLayout.createSequentialGroup()
                            .addComponent(lbDocumento3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(textDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelDatosPersonalesLayout.createSequentialGroup()
                            .addComponent(lbDocumento2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(textTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ckUsuario)
                .addContainerGap())
        );
        panelDatosPersonalesLayout.setVerticalGroup(
            panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ckUsuario))
            .addGroup(panelDatosPersonalesLayout.createSequentialGroup()
                .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombres1)
                    .addComponent(textNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbApellidos1)
                    .addComponent(textApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDocumento1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDocumento2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDocumento3))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Salir");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDatosPersonales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDatosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDatosPersonales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(panelDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void llenarComboRoles() {

        // Agregando los elementos del JComboBox de los roles
        ArrayList<RolDTO> listaRoles = servicio.listarRoles();

        listaRoles.forEach((rol) -> {
            comboRoles.addItem(rol);
        });
    }

    private void textNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombresActionPerformed

    private void textApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textApellidosActionPerformed

    private void textDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDocumentoActionPerformed

    private void textNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreUsuarioActionPerformed

    private void comboRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRolesActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cerrar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // Registrando usuario
        String nombres = textNombres.getText();
        String apellidos = textApellidos.getText();
        String documento = textDocumento.getText();
        String telefono=textTelefono.getText();
        String direccion =textDireccion.getText();
        long rol = 0;

        String nombreUsuario = "";
        String contrasena = "";
        String confirmarContrasena = "";
        if (ckUsuario.isSelected()) {
            nombreUsuario = textNombreUsuario.getText();
            contrasena = String.copyValueOf(passContrasena.getPassword());
            confirmarContrasena = String.copyValueOf(passConfirmarContrasena.getPassword());

            if (!(nombres.length() > 2 && apellidos.length() > 2 && contrasena.length() > 2 && confirmarContrasena.length() > 2 && nombreUsuario.length() > 2)) {
                mostrarMensaje("Falta uno o más datos por ingresar");
                return;
            }

            if (!textDocumento.getText().matches(REGEX_ENTERO_POSITIVO)) {
                mostrarMensaje("Solo se permiten números para el documento");
                textDocumento.requestFocus();
                return;
            } else {
                documento = textDocumento.getText();
            }

            //Extrayendo el ID desde el objeto almacenado en el item
            if (!String.valueOf(comboRoles.getSelectedItem()).equals("Seleccione un rol")) {
                RolDTO rolDTO = (RolDTO) comboRoles.getSelectedItem();
                rol = rolDTO.getId();
            } else {
                mostrarMensaje("Seleccione un rol");
                comboRoles.requestFocus();
                return;
            }

            if (contrasena.equals(confirmarContrasena)) {
                if (!servicio.validarCedulaUsuario(textDocumento.getText())) {
                    if (!servicio.validarUsuario(textNombreUsuario.getText())) {
                        if (servicio.registrarUsuario(nombres, apellidos, documento, nombreUsuario, contrasena, rol,telefono,direccion)) {
                            
                            long id = servicio.consultarUltimoUsuario();
                            double total = 0.0;
                            double total_debe = 0.0;
                            double total_abono = 0.0;
                            servicio.crearAbonoUsuario(id, total, total_debe, total_abono);
                            mostrarMensaje("Usuario registrado satisfactoriamente");

                            vistaUsuarios.actualizarTablaUsuarios();
                            this.dispose();
                        } else {
                            mostrarMensaje("No se pudo registrar el usuario");
                        }
                    } else {
                        mostrarMensaje("Nombre de usuario ya existe");
                    }
                } else {
                    mostrarMensaje("Documento ya existe");
                }
            } else {
                mostrarMensaje("Las contraseñas no coinciden");
            }
        } else {
            String docum = textDocumento.getText();
            
                RolDTO rolDTO = (RolDTO) comboRoles.getSelectedItem();
                rol = rolDTO.getId();
                System.out.println(rol+"rol");
                if (servicio.registrarUsuario(nombres, apellidos, documento, "", "", rol,telefono,direccion)) {
                    UsuarioDTO usuario = servicio.buscarUsuarioCedula(documento);
                    long id = servicio.consultarUltimoUsuario();
                    double total = 0.0;
                    double total_debe = 0.0;
                    double total_abono = 0.0;
                    servicio.crearAbonoUsuario(id, total, total_debe, total_abono);
                    mostrarMensaje("Usuario registrado satisfactoriamente 2");

                    vistaUsuarios.actualizarTablaUsuarios();
                    this.dispose();
                }
            
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:

        llenarComboRoles();
    }//GEN-LAST:event_formInternalFrameOpened

    private void ckUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckUsuarioActionPerformed

        if (ckUsuario.isSelected()) {

            lbNombreUsuario.setVisible(true);
            lbContrasena.setVisible(true);
            lbConfirmarContrasena.setVisible(true);
            textNombreUsuario.setVisible(true);
            passContrasena.setVisible(true);
            passConfirmarContrasena.setVisible(true);
            
        } else {

            lbNombreUsuario.setVisible(false);
            lbContrasena.setVisible(false);
            lbConfirmarContrasena.setVisible(false);
            textNombreUsuario.setVisible(false);
            passContrasena.setVisible(false);
            passConfirmarContrasena.setVisible(false);
        }

    }//GEN-LAST:event_ckUsuarioActionPerformed

    private void textTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTelefonoActionPerformed

    private void textDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDireccionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JCheckBox ckUsuario;
    private javax.swing.JComboBox<Object> comboRoles;
    private javax.swing.JLabel lbApellidos1;
    private javax.swing.JLabel lbConfirmarContrasena;
    private javax.swing.JLabel lbContrasena;
    private javax.swing.JLabel lbDocumento1;
    private javax.swing.JLabel lbDocumento2;
    private javax.swing.JLabel lbDocumento3;
    private javax.swing.JLabel lbNombreUsuario;
    private javax.swing.JLabel lbNombres1;
    private javax.swing.JLabel lbRol;
    private javax.swing.JPanel panelDatosPersonales;
    private javax.swing.JPanel panelDatosUsuario;
    private javax.swing.JPasswordField passConfirmarContrasena;
    private javax.swing.JPasswordField passContrasena;
    private javax.swing.JTextField textApellidos;
    private javax.swing.JTextField textDireccion;
    private javax.swing.JTextField textDocumento;
    private javax.swing.JTextField textNombreUsuario;
    private javax.swing.JTextField textNombres;
    private javax.swing.JTextField textTelefono;
    // End of variables declaration//GEN-END:variables

}
