package com.zapateria.main.view;


import com.zapateria.main.dto.FacturaDTO;
import com.zapateria.main.view.MarcoInternoPersonalizado;
import com.zapateria.main.view.TablaPersonalizada;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JHON
 */
public class ifrmVentas2 extends MarcoInternoPersonalizado {

    private static final long serialVersionUID = -5239709877812395442L;
    private static final String VENTAS = "VENTAS";
    private DefaultTableModel dtbmVentas;

    
   
        
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVentas = new javax.swing.JPanel();
        btnNuevaFactura = new javax.swing.JButton();
        comboBuscarFactura = new javax.swing.JComboBox<>();
        lbBuscarFactura = new javax.swing.JLabel();
        panelVentaProductos = new javax.swing.JPanel();
        spVentaProductos = new javax.swing.JScrollPane();
        tbVentas = new TablaPersonalizada();
        lbBuscarCliente1 = new javax.swing.JLabel();
        comboBuscarProducto = new javax.swing.JComboBox<>();
        btnQuitarProducto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        texTotalPagado = new javax.swing.JTextField();
        lbTotalPagado = new javax.swing.JLabel();
        lbTotalPagar = new javax.swing.JLabel();
        lbIVA = new javax.swing.JLabel();
        lbSubtotal = new javax.swing.JLabel();
        textSubtotal = new javax.swing.JTextField();
        textIVA = new javax.swing.JTextField();
        texTotalPagar = new javax.swing.JTextField();
        btnCobrar = new javax.swing.JButton();
        panelCliente = new javax.swing.JPanel();
        textDocumento = new javax.swing.JTextField();
        lbDocumento = new javax.swing.JLabel();
        lbNombres = new javax.swing.JLabel();
        textNombres = new javax.swing.JTextField();
        lbTelefono = new javax.swing.JLabel();
        textTelefono = new javax.swing.JTextField();
        textDireccion = new javax.swing.JTextField();
        lbDireccion = new javax.swing.JLabel();
        lbApellidos = new javax.swing.JLabel();
        textApellidos = new javax.swing.JTextField();
        lbDocumento1 = new javax.swing.JLabel();
        textCodigoCliente = new javax.swing.JTextField();
        comboBuscarCliente = new javax.swing.JComboBox<>();
        lbBuscarCliente = new javax.swing.JLabel();
        panelFactura = new javax.swing.JPanel();
        lblNumeroFactura = new javax.swing.JLabel();
        textNumeroFactura = new javax.swing.JTextField();
        lbFormaDePago = new javax.swing.JLabel();
        comboFormaDePago = new javax.swing.JComboBox<>();
        lbFormaDePago2 = new javax.swing.JLabel();
        dateFechaEntrega = new com.github.lgooddatepicker.components.DatePicker();
        comboEstadoFactura = new javax.swing.JComboBox<>();
        lbEstadoFactura = new javax.swing.JLabel();

        panelVentas.setMinimumSize(new java.awt.Dimension(300, 300));
        panelVentas.setPreferredSize(new java.awt.Dimension(1600, 400));

        btnNuevaFactura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNuevaFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/zapateria/main/images/agregarfac2.png"))); // NOI18N
        btnNuevaFactura.setText("Nueva factura");
        btnNuevaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaFacturaActionPerformed(evt);
            }
        });

        comboBuscarFactura.setEditable(true);
        comboBuscarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBuscarFacturaActionPerformed(evt);
            }
        });

        lbBuscarFactura.setText("Buscar Factura:");

        panelVentaProductos.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos"));
        panelVentaProductos.setMaximumSize(new java.awt.Dimension(2000, 2000));
        panelVentaProductos.setMinimumSize(new java.awt.Dimension(100, 100));

        spVentaProductos.setPreferredSize(new java.awt.Dimension(100, 100));

        tbVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio unitario", "Comentario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbVentas.setEnabled(false);
        tbVentas.setMaximumSize(new java.awt.Dimension(2000, 2000));
        tbVentas.setOpaque(false);
        spVentaProductos.setViewportView(tbVentas);

        lbBuscarCliente1.setText("Buscar y agregar producto:");

        comboBuscarProducto.setEnabled(false);
        comboBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBuscarProductoActionPerformed(evt);
            }
        });

        btnQuitarProducto.setText("Quitar");
        btnQuitarProducto.setEnabled(false);
        btnQuitarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVentaProductosLayout = new javax.swing.GroupLayout(panelVentaProductos);
        panelVentaProductos.setLayout(panelVentaProductosLayout);
        panelVentaProductosLayout.setHorizontalGroup(
            panelVentaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentaProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVentaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVentaProductosLayout.createSequentialGroup()
                        .addComponent(lbBuscarCliente1)
                        .addGap(18, 18, 18)
                        .addComponent(comboBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuitarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(spVentaProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelVentaProductosLayout.setVerticalGroup(
            panelVentaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVentaProductosLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(panelVentaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBuscarCliente1)
                    .addComponent(btnQuitarProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spVentaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        comboBuscarProducto.getAccessibleContext().setAccessibleDescription("");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        texTotalPagado.setText("0");

        lbTotalPagado.setText("Total pagado:");

        lbTotalPagar.setText("Total a pagar:");

        lbIVA.setText("Iva al 19%:");

        lbSubtotal.setText("Subtotal:");

        textSubtotal.setEditable(false);

        textIVA.setEditable(false);

        texTotalPagar.setEditable(false);

        btnCobrar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnCobrar.setText("Registrar");
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTotalPagar)
                    .addComponent(lbIVA)
                    .addComponent(lbSubtotal)
                    .addComponent(lbTotalPagado))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(texTotalPagar, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textIVA, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textSubtotal, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texTotalPagado, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSubtotal))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIVA))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTotalPagar))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texTotalPagado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTotalPagado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCobrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        textDocumento.setEditable(false);
        textDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDocumentoActionPerformed(evt);
            }
        });

        lbDocumento.setText("Documento:");

        lbNombres.setText("Nombres:");

        textNombres.setEditable(false);
        textNombres.setOpaque(false);
        textNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombresActionPerformed(evt);
            }
        });

        lbTelefono.setText("Teléfono:");

        textTelefono.setEditable(false);
        textTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTelefonoActionPerformed(evt);
            }
        });

        textDireccion.setEditable(false);
        textDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDireccionActionPerformed(evt);
            }
        });

        lbDireccion.setText("Dirección:");

        lbApellidos.setText("Apellidos:");

        textApellidos.setEditable(false);
        textApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textApellidosActionPerformed(evt);
            }
        });

        lbDocumento1.setText("Cod. cliente:");
        lbDocumento1.setOpaque(true);

        textCodigoCliente.setEditable(false);

        comboBuscarCliente.setEnabled(false);

        lbBuscarCliente.setText("Buscar cliente:");

        javax.swing.GroupLayout panelClienteLayout = new javax.swing.GroupLayout(panelCliente);
        panelCliente.setLayout(panelClienteLayout);
        panelClienteLayout.setHorizontalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelClienteLayout.createSequentialGroup()
                                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbDocumento1)
                                            .addComponent(lbDocumento, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(lbNombres, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(lbApellidos, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textApellidos)
                                    .addComponent(textDocumento)
                                    .addComponent(textNombres)
                                    .addComponent(textCodigoCliente)))
                            .addGroup(panelClienteLayout.createSequentialGroup()
                                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelClienteLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(lbTelefono))
                                    .addGroup(panelClienteLayout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(lbDireccion)))
                                .addGap(8, 8, 8)
                                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textTelefono)
                                    .addComponent(textDireccion)))))
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lbBuscarCliente)
                        .addGap(10, 10, 10)
                        .addComponent(comboBuscarCliente, 0, 251, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelClienteLayout.setVerticalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBuscarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDocumento1)
                    .addComponent(textCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDocumento)
                    .addComponent(textDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombres)
                    .addComponent(textNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbApellidos)
                    .addComponent(textApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefono)
                    .addComponent(textTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDireccion)
                    .addComponent(textDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        panelFactura.setBorder(javax.swing.BorderFactory.createTitledBorder("Factura"));

        lblNumeroFactura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNumeroFactura.setText("N° Factura");

        textNumeroFactura.setEditable(false);

        lbFormaDePago.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbFormaDePago.setText("Forma de pago:");

        comboFormaDePago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CONTADO", "CUOTAS" }));
        comboFormaDePago.setEnabled(false);
        comboFormaDePago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFormaDePagoActionPerformed(evt);
            }
        });

        lbFormaDePago2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbFormaDePago2.setText("Fecha de entrega:");

        dateFechaEntrega.setEnabled(false);

        comboEstadoFactura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DEPOSITO", "ENTREGADO", "PROCESO" }));
        comboEstadoFactura.setEnabled(false);

        lbEstadoFactura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbEstadoFactura.setText("Estado:");

        javax.swing.GroupLayout panelFacturaLayout = new javax.swing.GroupLayout(panelFactura);
        panelFactura.setLayout(panelFacturaLayout);
        panelFacturaLayout.setHorizontalGroup(
            panelFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFacturaLayout.createSequentialGroup()
                .addComponent(lblNumeroFactura)
                .addGap(10, 10, 10)
                .addComponent(textNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbFormaDePago)
                .addGap(10, 10, 10)
                .addComponent(comboFormaDePago, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbEstadoFactura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboEstadoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbFormaDePago2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelFacturaLayout.setVerticalGroup(
            panelFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFacturaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroFactura)
                    .addComponent(textNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFormaDePago)
                    .addComponent(comboFormaDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEstadoFactura)
                    .addComponent(comboEstadoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFormaDePago2)
                    .addComponent(dateFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelVentasLayout = new javax.swing.GroupLayout(panelVentas);
        panelVentas.setLayout(panelVentasLayout);
        panelVentasLayout.setHorizontalGroup(
            panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVentasLayout.createSequentialGroup()
                        .addComponent(btnNuevaFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelVentaProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVentasLayout.createSequentialGroup()
                        .addComponent(lbBuscarFactura)
                        .addGap(10, 10, 10)
                        .addComponent(comboBuscarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(179, 179, 179))
        );
        panelVentasLayout.setVerticalGroup(
            panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentasLayout.createSequentialGroup()
                .addGroup(panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVentasLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNuevaFactura)
                            .addGroup(panelVentasLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comboBuscarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbBuscarFactura)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVentasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVentasLayout.createSequentialGroup()
                        .addComponent(panelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelVentaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        if (SESION_USUARIO.isVistaPermitida(VENTAS)) {

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 1630, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 625, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
            );

        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaFacturaActionPerformed

        this.textNumeroFactura.setEditable(true);
        this.comboFormaDePago.setEnabled(true);
        this.comboEstadoFactura.setEnabled(true);
        this.dateFechaEntrega.setEnabled(true);
        this.comboBuscarCliente.setEditable(true);
        this.comboBuscarCliente.setEnabled(true);
        this.comboBuscarProducto.setEditable(true);
        this.comboBuscarProducto.setEnabled(true);
        this.btnQuitarProducto.setEnabled(true);
        this.tbVentas.setEnabled(true);
    }//GEN-LAST:event_btnNuevaFacturaActionPerformed

    private void comboBuscarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBuscarFacturaActionPerformed

    }//GEN-LAST:event_comboBuscarFacturaActionPerformed

    private void comboBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBuscarProductoActionPerformed

    }//GEN-LAST:event_comboBuscarProductoActionPerformed

    private void btnQuitarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarProductoActionPerformed

        int filaSeleccionada = tbVentas.getSelectedRow();
        Object objId = tbVentas.getValueAt(filaSeleccionada, 0);
        if (objId == null) {
            return;
        }
        long id = Long.parseLong(String.valueOf(objId));
        dtbmVentas.removeRow(filaSeleccionada);
      
    }//GEN-LAST:event_btnQuitarProductoActionPerformed

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
       
    }//GEN-LAST:event_btnCobrarActionPerformed

    private void textDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDocumentoActionPerformed

    }//GEN-LAST:event_textDocumentoActionPerformed

    private void textNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombresActionPerformed
        textNombres.setEditable(true);
    }//GEN-LAST:event_textNombresActionPerformed

    private void textTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTelefonoActionPerformed
        textTelefono.setEditable(true);
    }//GEN-LAST:event_textTelefonoActionPerformed

    private void textDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDireccionActionPerformed
        textDireccion.setEditable(true);
    }//GEN-LAST:event_textDireccionActionPerformed

    private void textApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textApellidosActionPerformed
        textApellidos.setEditable(true);
    }//GEN-LAST:event_textApellidosActionPerformed

    private void comboFormaDePagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFormaDePagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFormaDePagoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnNuevaFactura;
    private javax.swing.JButton btnQuitarProducto;
    private javax.swing.JComboBox<Object> comboBuscarCliente;
    private javax.swing.JComboBox<Object> comboBuscarFactura;
    private javax.swing.JComboBox<Object> comboBuscarProducto;
    private javax.swing.JComboBox<Object> comboEstadoFactura;
    private javax.swing.JComboBox<Object> comboFormaDePago;
    private com.github.lgooddatepicker.components.DatePicker dateFechaEntrega;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbApellidos;
    private javax.swing.JLabel lbBuscarCliente;
    private javax.swing.JLabel lbBuscarCliente1;
    private javax.swing.JLabel lbBuscarFactura;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbDocumento;
    private javax.swing.JLabel lbDocumento1;
    private javax.swing.JLabel lbEstadoFactura;
    private javax.swing.JLabel lbFormaDePago;
    private javax.swing.JLabel lbFormaDePago2;
    private javax.swing.JLabel lbIVA;
    private javax.swing.JLabel lbNombres;
    private javax.swing.JLabel lbSubtotal;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JLabel lbTotalPagado;
    private javax.swing.JLabel lbTotalPagar;
    private javax.swing.JLabel lblNumeroFactura;
    private javax.swing.JPanel panelCliente;
    private javax.swing.JPanel panelFactura;
    private javax.swing.JPanel panelVentaProductos;
    private javax.swing.JPanel panelVentas;
    private javax.swing.JScrollPane spVentaProductos;
    private javax.swing.JTable tbVentas;
    private javax.swing.JTextField texTotalPagado;
    private javax.swing.JTextField texTotalPagar;
    private javax.swing.JTextField textApellidos;
    private javax.swing.JTextField textCodigoCliente;
    private javax.swing.JTextField textDireccion;
    private javax.swing.JTextField textDocumento;
    private javax.swing.JTextField textIVA;
    private javax.swing.JTextField textNombres;
    private javax.swing.JTextField textNumeroFactura;
    private javax.swing.JTextField textSubtotal;
    private javax.swing.JTextField textTelefono;
    // End of variables declaration//GEN-END:variables
}
