

DROP SCHEMA IF EXISTS ZAPATERIA;
CREATE SCHEMA  ZAPATERIA;
SET SCHEMA = ZAPATERIA;


-- Creando e inicializando la búsqueda de texto completo 'FULL TEXT' para la base de datos 
CREATE ALIAS IF NOT EXISTS FT_INIT FOR "org.h2.fulltext.FullText.init";
CALL FT_INIT();

CREATE TABLE ROLES (
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  ROL VARCHAR(100) UNIQUE NOT NULL,
  VALOR DECIMAL(21,2) NOT NULL DEFAULT 0
 
);
-- CREATE UNIQUE INDEX UNICO_ROL ON ROLES(ROL);

CREATE TABLE VISTAS(
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  VISTA VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE PERMISOS (
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  ROLES_ID INT(5) UNSIGNED NOT NULL,
  VISTAS_ID INT(5) UNSIGNED NOT NULL,
  CONSTRAINT ROL_PERMISOS
  FOREIGN KEY(ROLES_ID) REFERENCES ROLES(ID)
  ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT VISTA_PERMISOS
  FOREIGN KEY(VISTAS_ID) REFERENCES VISTAS(ID)
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE USUARIOS(
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  NOMBRES VARCHAR(100) NOT NULL,
  APELLIDOS VARCHAR(100) NOT NULL,
  DOCUMENTO VARCHAR(50) NOT NULL,
  NOMBRE_USUARIO VARCHAR(100),
  TELEFONO VARCHAR(100),
  ESTADO ENUM('ACTIVO','INACTIVO','ELIMINADO') NOT NULL DEFAULT 0,
  CONTRASENA VARCHAR(64) ,
  ROLES_ID INT(5) UNSIGNED NOT NULL,
  FECHA_INGRESO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DIRECCION VARCHAR(100),
  CONSTRAINT ROL_USUARIOS
  FOREIGN KEY(ROLES_ID) REFERENCES ROLES(ID)
  ON DELETE CASCADE ON UPDATE CASCADE
);
-- Creando indexado para la busqueda 'FULL TEXT'
CALL FT_DROP_INDEX('ZAPATERIA','USUARIOS');
CALL FT_CREATE_INDEX('ZAPATERIA', 'USUARIOS', NULL);



CREATE TABLE PRODUCTOS(
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  NOMBRE VARCHAR(150) NOT NULL UNIQUE,
  PRECIO_UNITARIO DECIMAL(21,2) NOT NULL DEFAULT 0
);
-- Creando indexado para la busqueda 'FULL TEXT'
CALL FT_DROP_INDEX('ZAPATERIA','PRODUCTOS');
CALL FT_CREATE_INDEX('ZAPATERIA', 'PRODUCTOS', NULL);

CREATE TABLE CLIENTES (
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  DOCUMENTO VARCHAR(50),
  NOMBRES VARCHAR(50) NOT NULL,
  APELLIDOS VARCHAR(50) NOT NULL,
  DIRECCION VARCHAR(150),
  TELEFONO VARCHAR(50),
  FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- Creando indexado para la busqueda 'FULL TEXT'
CALL FT_DROP_INDEX('ZAPATERIA','CLIENTES');
CALL FT_CREATE_INDEX('ZAPATERIA', 'CLIENTES', NULL);

CREATE TABLE FACTURAS (
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  FORMA_DE_PAGO ENUM('CONTADO','CUOTAS') NOT NULL DEFAULT 0,
  FECHA_FACTURA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  IVA DECIMAL(21,2) NOT NULL DEFAULT 0,
  TOTAL_A_PAGAR DECIMAL(22,2) NOT NULL DEFAULT 0,
  TOTAL_PAGADO DECIMAL(22,2) NOT NULL DEFAULT 0,
  FECHA_ENTREGA DATE NOT NULL DEFAULT CURRENT_DATE,
  CLIENTES_ID BIGINT(18) UNSIGNED NOT NULL,
  USUARIOS_ID BIGINT(18) UNSIGNED NOT NULL,
  NUMERO_CUOTAS BIGINT(18)DEFAULT 0,
  CUOTAS_PAGADAS BIGINT(18)DEFAULT 0,
  CONSTRAINT CLIENTE_VENTAS
  FOREIGN KEY(CLIENTES_ID) REFERENCES CLIENTES(ID)
  ON DELETE  CASCADE ON UPDATE CASCADE,
  CONSTRAINT USUARIO_VENTAS
  FOREIGN KEY(USUARIOS_ID) REFERENCES USUARIOS(ID)
  ON DELETE CASCADE ON UPDATE CASCADE
 
);

-- Creando indexado para la busqueda 'FULL TEXT'
CALL FT_DROP_INDEX('ZAPATERIA','FACTURAS');
CALL FT_CREATE_INDEX('ZAPATERIA', 'FACTURAS', NULL);

CREATE TABLE VENTAS(
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  CANTIDAD BIGINT(18) UNSIGNED NOT NULL DEFAULT 0,
  ESTADO ENUM('DEPOSITO','ENTREGADO','PROCESO') NOT NULL DEFAULT 0,
  COMENTARIO VARCHAR(150) NOT NULL DEFAULT 'Ninguno',
  FACTURAS_ID BIGINT(18) UNSIGNED NOT NULL,
  MATERIAL_ID BIGINT(18) UNSIGNED NOT NULL,
  PRECIO DECIMAL(21,2) NOT NULL DEFAULT 0
  CONSTRAINT FACTURA_VENTAS
  FOREIGN KEY(FACTURAS_ID) REFERENCES FACTURAS(ID)
  ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT PRODUCTO_VENTAS
  FOREIGN KEY(MATERIAL_ID) REFERENCES MATERIALES(ID)
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE FACTURAS2 (
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  
  FECHA_FACTURA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  IVA DECIMAL(21,2) NOT NULL DEFAULT 0,
  TOTAL_A_PAGAR DECIMAL(22,2) NOT NULL DEFAULT 0,
  TOTAL_PAGADO DECIMAL(22,2) NOT NULL DEFAULT 0,
  CLIENTES_ID BIGINT(18) UNSIGNED NOT NULL,
  USUARIOS_ID BIGINT(18) UNSIGNED NOT NULL,
  CONSTRAINT CLIENTE_VENTAS2
  FOREIGN KEY(CLIENTES_ID) REFERENCES CLIENTES(ID)
  ON DELETE  CASCADE ON UPDATE CASCADE,
  CONSTRAINT USUARIO_VENTAS2
  FOREIGN KEY(USUARIOS_ID) REFERENCES USUARIOS(ID)
  ON DELETE CASCADE ON UPDATE CASCADE
 
);

-- Creando indexado para la busqueda 'FULL TEXT'
CALL FT_DROP_INDEX('ZAPATERIA','FACTURAS2');
CALL FT_CREATE_INDEX('ZAPATERIA', 'FACTURAS2', NULL);

CREATE TABLE VENTAS2(
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ESTADO ENUM('DEPOSITO','ENTREGADO','PROCESO') NOT NULL DEFAULT 0,
  FORMA_DE_PAGO ENUM('CONTADO','CUOTAS') NOT NULL DEFAULT 0,
  CLIENTES_ID BIGINT(18) UNSIGNED NOT NULL,
  FACTURAS_ID BIGINT(18) UNSIGNED NOT NULL,
  USUARIOS_ID BIGINT(18) UNSIGNED NOT NULL,
  REGISTRO_ID BIGINT(18) UNSIGNED NOT NULL,
  CANTIDAD BIGINT(18) UNSIGNED NOT NULL DEFAULT 0,
  MATERIAL_ID BIGINT(18) UNSIGNED NOT NULL,
  COMENTARIO VARCHAR(150) NOT NULL DEFAULT 'Ninguno',
  PRECIO DECIMAL(21,2) NOT NULL DEFAULT 0,
  NUMERO_CUOTAS BIGINT(18)DEFAULT 0,
  CUOTAS_PAGADAS BIGINT(18)DEFAULT 0,
  FECHA_ENTREGA DATE NOT NULL DEFAULT CURRENT_DATE,
  TOTAL_A_PAGAR DECIMAL(22,2) NOT NULL DEFAULT 0,
  TOTAL_PAGADO DECIMAL(22,2) NOT NULL DEFAULT 0,
  IVA DECIMAL(21,2) NOT NULL DEFAULT 0,
  CONSTRAINT CLIENTE_V
  FOREIGN KEY(CLIENTES_ID) REFERENCES CLIENTES(ID)
  ON DELETE  CASCADE ON UPDATE CASCADE,
  CONSTRAINT USUARIO_V
  FOREIGN KEY(USUARIOS_ID) REFERENCES USUARIOS(ID)
  ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT PRODUCTO_V
  FOREIGN KEY(MATERIAL_ID) REFERENCES MATERIALES(ID)
  ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FACTURA_V
  FOREIGN KEY(FACTURAS_ID) REFERENCES FACTURAS2(ID)
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE VENTAS3(
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  CLIENTES_ID BIGINT(18) UNSIGNED NOT NULL,
  FACTURAS_ID BIGINT(18) UNSIGNED NOT NULL,
  USUARIOS_ID BIGINT(18) UNSIGNED NOT NULL,
  REGISTRO_ID BIGINT(18) UNSIGNED NOT NULL,
  CONSTRAINT CLIENTE_V3
  FOREIGN KEY(CLIENTES_ID) REFERENCES CLIENTES(ID)
  ON DELETE  CASCADE ON UPDATE CASCADE,
  CONSTRAINT USUARIO_V3
  FOREIGN KEY(USUARIOS_ID) REFERENCES USUARIOS(ID)
  ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT PRODUCTO_V3
  FOREIGN KEY(REGISTRO_ID) REFERENCES REGISTRO(ID)
  ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FACTURA_V3
  FOREIGN KEY(FACTURAS_ID) REFERENCES FACTURAS3(ID)
  ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE FACTURAS3 (
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  FORMA_DE_PAGO ENUM('CONTADO','CREDITO') NOT NULL DEFAULT 0,
  FECHA_FACTURA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  IVA DECIMAL(21,2) NOT NULL DEFAULT 0,
  TOTAL_A_PAGAR DECIMAL(22,2) NOT NULL DEFAULT 0,
  TOTAL_PAGADO DECIMAL(22,2) NOT NULL DEFAULT 0,
  CLIENTES_ID BIGINT(18) UNSIGNED NOT NULL,
  USUARIOS_ID BIGINT(18) UNSIGNED NOT NULL,
  FACTURA VARCHAR(150) NOT NULL DEFAULT '-',
  CONSTRAINT CLIENTE_VENTAS3
  FOREIGN KEY(CLIENTES_ID) REFERENCES CLIENTES(ID)
  ON DELETE  CASCADE ON UPDATE CASCADE,
  CONSTRAINT USUARIO_VENTAS3
  FOREIGN KEY(USUARIOS_ID) REFERENCES USUARIOS(ID)
  ON DELETE CASCADE ON UPDATE CASCADE
 
);



CREATE TABLE REGISTRO (
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ESTADO ENUM('DEPOSITO','ENTREGADO','PROCESO') NOT NULL DEFAULT 0,
  CLIENTES_ID BIGINT(18) UNSIGNED NOT NULL,
  USUARIOS_ID BIGINT(18) UNSIGNED NOT NULL,
  CANTIDAD BIGINT(18) UNSIGNED NOT NULL DEFAULT 0,
  MATERIAL_ID BIGINT(18) UNSIGNED NOT NULL,
  COMENTARIO VARCHAR(150) NOT NULL DEFAULT 'Ninguno',
  PRECIO DECIMAL(21,2) NOT NULL DEFAULT 0,
  IMPRESO BIGINT(18)DEFAULT 0,
  FACTURAS_ID BIGINT(18)DEFAULT 0,
  FECHA_ENTREGA DATE NOT NULL DEFAULT CURRENT_DATE,
  TOTAL_A_PAGAR DECIMAL(22,2) NOT NULL DEFAULT 0,
  IVA DECIMAL(21,2) NOT NULL DEFAULT 0,
  CONSTRAINT CLIENTE_VENTA
  FOREIGN KEY(CLIENTES_ID) REFERENCES CLIENTES(ID)
  ON DELETE  CASCADE ON UPDATE CASCADE,
  CONSTRAINT USUARIO_VENTA
  FOREIGN KEY(USUARIOS_ID) REFERENCES USUARIOS(ID)
  ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT PRODUCTO_VENTA
  FOREIGN KEY(MATERIAL_ID) REFERENCES MATERIALES(ID)
  ON DELETE CASCADE ON UPDATE CASCADE
);

-- Creando indexado para la busqueda 'FULL TEXT'
CALL FT_DROP_INDEX('ZAPATERIA','REGISTRO');
CALL FT_CREATE_INDEX('ZAPATERIA', 'REGISTRO', NULL);

CREATE TABLE REGISTRO2 (
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ESTADO ENUM('DEPOSITO','ENTREGADO','PROCESO') NOT NULL DEFAULT 0,
  FORMA_DE_PAGO ENUM('CONTADO','CUOTAS') NOT NULL DEFAULT 0,
  CLIENTES_ID BIGINT(18) UNSIGNED NOT NULL,
  USUARIOS_ID BIGINT(18) UNSIGNED NOT NULL,
  CANTIDAD BIGINT(18) UNSIGNED NOT NULL DEFAULT 0,
  MATERIAL_ID BIGINT(18) UNSIGNED NOT NULL,
  COMENTARIO VARCHAR(150) NOT NULL DEFAULT 'Ninguno',
  PRECIO DECIMAL(21,2) NOT NULL DEFAULT 0,
  NUMERO_CUOTAS BIGINT(18)DEFAULT 0,
  CUOTAS_PAGADAS BIGINT(18)DEFAULT 0,
  FECHA_ENTREGA DATE NOT NULL DEFAULT CURRENT_DATE,
  TOTAL_A_PAGAR DECIMAL(22,2) NOT NULL DEFAULT 0,
  TOTAL_PAGADO DECIMAL(22,2) NOT NULL DEFAULT 0,
  IVA DECIMAL(21,2) NOT NULL DEFAULT 0,
  CONSTRAINT CLIENTE_VENT
  FOREIGN KEY(CLIENTES_ID) REFERENCES CLIENTES(ID)
  ON DELETE  CASCADE ON UPDATE CASCADE,
  CONSTRAINT USUARIO_VENT
  FOREIGN KEY(USUARIOS_ID) REFERENCES USUARIOS(ID)
  ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT PRODUCTO_VENT
  FOREIGN KEY(MATERIAL_ID) REFERENCES MATERIALES(ID)
  ON DELETE CASCADE ON UPDATE CASCADE
);

-- Creando indexado para la busqueda 'FULL TEXT'
CALL FT_DROP_INDEX('ZAPATERIA','REGISTRO2');
CALL FT_CREATE_INDEX('ZAPATERIA', 'REGISTRO2', NULL);




CREATE TABLE MATERIAS_REGISTRO(
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  CANTIDAD BIGINT(18) UNSIGNED NOT NULL DEFAULT 0,
  COMENTARIO VARCHAR(150) NOT NULL DEFAULT 'Ninguno',
  REGISTRO_ID BIGINT(18) UNSIGNED NOT NULL,
  MATERIAL_ID BIGINT(18) UNSIGNED NOT NULL,
  PRECIO DECIMAL(21,2) NOT NULL DEFAULT 0
  CONSTRAINT REGISTRO_VENTAS
  FOREIGN KEY(REGISTRO_ID) REFERENCES REGISTRO(ID)
  ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT PRODUCTO_VENTAS
  FOREIGN KEY(MATERIAL_ID) REFERENCES MATERIALES(ID)
  ON DELETE CASCADE ON UPDATE CASCADE
);



CREATE TABLE IMPUESTOS(
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  NOMBRE VARCHAR(150) UNIQUE NOT NULL,
  VALOR DECIMAL(21,2) NOT NULL DEFAULT 0
);

CREATE TABLE PAGOS (
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  ABONO DECIMAL(22,2) NOT NULL,
  FECHA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FACTURAS_ID BIGINT(18) UNSIGNED NOT NULL,
  CONSTRAINT FACTURA_PAGOS
  FOREIGN KEY(FACTURAS_ID) REFERENCES FACTURAS3(ID)
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PAGOSPROV (
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  ABONO DECIMAL(22,2) NOT NULL,
  FECHA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  COMPRA_ID BIGINT(18) UNSIGNED NOT NULL,
  CONSTRAINT FACTURA_PAGOS
  FOREIGN KEY(COMPRA_ID) REFERENCES COMPRAS(ID)
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CUENTAS (
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  CUENTA VARCHAR(50),
  DESCRIPCION VARCHAR(50),
  SALDO DECIMAL(21,2),
  CONTRACUENTA TINYINT(1) NOT NULL,
  VISIBLE TINYINT(1) NOT NULL,
  PASIVO TINYINT(1) NOT NULL,
  CONT VARCHAR(4),
  NEG VARCHAR(1)
);

CREATE TABLE AUXILIARES (
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  FECHA TIMESTAMP,
  CONCEPTO VARCHAR(100),
  CREDITO DECIMAL(21,2),
  DEBITO DECIMAL(21,2),
  CIERRE TINYINT(1) NOT NULL,
  CONTRACUENTA INT(10),
  SALDON DECIMAL(21,2),
  SALDONC DECIMAL(21,2),
  CUENTAS_ID BIGINT(18) UNSIGNED NOT NULL,
  CONSTRAINT CUENTAS_AUXILIAR
  FOREIGN KEY(CUENTAS_ID) REFERENCES CUENTAS(ID)
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CIERRES (
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  FECHA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  AUXILIARES_ID BIGINT(18) NOT NULL,
  TOTABONO DECIMAL(21,2),
  TOTABONOANT DECIMAL(21,2),
  TERMINADO TINYINT(1) NOT NULL,
  CONSTRAINT AUXILIAR_CIERRES
  FOREIGN KEY(AUXILIARES_ID) REFERENCES AUXILIARES(ID)
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BALANCESANT (
  MES VARCHAR(50),
  CUENTA VARCHAR(50),
  SUBCUENTA VARCHAR(50),
  COD VARCHAR(4),
  DESCRIPCION VARCHAR(80),
  VALOR DECIMAL(21,2)
);

CREATE TABLE PROVEEDORES (
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  NOMBRE VARCHAR(50) UNIQUE NOT NULL,
  NIT VARCHAR(50) UNIQUE NOT NULL,
  DIRECCION VARCHAR(150) NOT NULL,
  TELEFONO VARCHAR(50) UNSIGNED,
  FECHA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE NOMBRE_GASTOS (
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  NOMBRE VARCHAR(50) UNIQUE NOT NULL,
  FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE NOMBRE_INGRESOS (
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  NOMBRE VARCHAR(50) NOT NULL,
  FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  NOMBRES_ID BIGINT(18) UNSIGNED NOT NULL,
  PAGO DECIMAL(22,2) NOT NULL,
  CONSTRAINT NOMBRES_INGRES
  FOREIGN KEY(NOMBRES_ID) REFERENCES NOMBRE_GASTOS(ID)
  ON UPDATE CASCADE ON DELETE CASCADE

);

CREATE TABLE INGRESOS_EGRESOS (
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  FECHA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ABONOS DECIMAL(21,2) NOT NULL DEFAULT 0,
  DEUDAS DECIMAL(21,2) NOT NULL DEFAULT 0,
  LIQUIDACIONES DECIMAL(21,2) NOT NULL DEFAULT 0,
  NOMINAS DECIMAL(21,2) NOT NULL DEFAULT 0,
  TOTAL_SALIO  DECIMAL(21,2) NOT NULL DEFAULT 0,
  TOTAL_ENTRO DECIMAL(21,2) NOT NULL DEFAULT 0,
  CAJA DECIMAL(21,2) NOT NULL DEFAULT 0,
  
  
 
);

CREATE TABLE MATERIALES (
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  NOMBRE VARCHAR(200) NOT NULL,
  PATRON VARCHAR(200) NOT NULL

);
-- Creando indexado para la busqueda 'FULL TEXT'
CALL FT_DROP_INDEX('ZAPATERIA','MATERIALES');
CALL FT_CREATE_INDEX('ZAPATERIA', 'MATERIALES', NULL);

CREATE TABLE MATERIALES_USADOS(
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  CANTIDAD BIGINT(18) UNSIGNED NOT NULL DEFAULT 1,
  FECHA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MATERIALES_ID BIGINT(18) UNSIGNED NOT NULL,
  CONSTRAINT MATERIALES_USADOS
  FOREIGN KEY(MATERIALES_ID) REFERENCES MATERIALES(ID)
  ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE COMPRAS (
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  CANTIDAD BIGINT(18) UNSIGNED NOT NULL DEFAULT 0,
  VALOR_UNITARIO DECIMAL(21,2) NOT NULL,
  VALOR_TOTAL DECIMAL(21,2) NOT NULL,
  ABONADO DECIMAL(21,2) DEFAULT 0,
  FECHA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PROVEEDORES_ID BIGINT(18) UNSIGNED NOT NULL,
  MATERIALES_ID BIGINT(18) UNSIGNED NOT NULL,
  CONSTRAINT PROVEEDOR_COMPRAS
  FOREIGN KEY(PROVEEDORES_ID) REFERENCES PROVEEDORES(ID)
  ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT MATERIAL_COMPRAS
  FOREIGN KEY(MATERIALES_ID) REFERENCES MATERIALES(ID)
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CUENTAG (
  COD VARCHAR(4) NOT NULL,
  CUENTAGEN VARCHAR(50),
  FIN VARCHAR(50),
  NEG VARCHAR(1)
);

CREATE TABLE NOMINAS (
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  NOMBRE VARCHAR(50),
  SALARIO DECIMAL(21,2),
  HD INT(10),
  HED INT(10),
  HEN INT(10),
  PRESTAMO DECIMAL(21,2),
  NOMINA VARCHAR(1),
  OTROS DECIMAL(21,2),
  SALDO DECIMAL(21,2)
);

CREATE TABLE NOMINA_USUARIO(
ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
ID_USUARIO BIGINT(18) UNSIGNED NOT NULL,
SALARIO_HORA DECIMAL(21,2) NOT NULL DEFAULT 0,
PAGO_TOTAL DECIMAL(21,2) NOT NULL DEFAULT 0,
FECHA_INICIO DATE NOT NULL ,
FECHA_FIN DATE NOT NULL DEFAULT CURRENT_DATE,
HORAS_TRABAJADAS BIGINT(18)NOT NULL DEFAULT 0,
DIAS_TRABAJADOS BIGINT(18)NOT NULL DEFAULT 0,
DIAS_EXTRAS BIGINT(18)NOT NULL DEFAULT 0,
ABONADO DECIMAL(21,2) NOT NULL DEFAULT 0,
CONSTRAINT NOMINA_USUARIOS
FOREIGN KEY(ID_USUARIO)REFERENCES USUARIOS(ID)
ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE PRESTAMO_USUARIO(
ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
ID_DEUDA BIGINT(18) UNSIGNED NOT NULL,
VALOR DECIMAL(21,2) NOT NULL DEFAULT 0,
FECHA DATE NOT NULL DEFAULT CURRENT_DATE,
CONCEPTO VARCHAR(50),
CONSTRAINT PRESTAMOS_USUARIOS
FOREIGN KEY(ID_DEUDA) REFERENCES ABONO_PRESTAMO(ID)
ON DELETE CASCADE ON UPDATE CASCADE


);


CREATE TABLE ZAPATERIA.ABONO_USUARIO(
ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
ID_DEUDA BIGINT(18)UNSIGNED NOT NULL,
VALOR DECIMAL(21,2) NOT NULL DEFAULT 0,
FECHA DATE NOT NULL DEFAULT CURRENT_DATE,
CONSTRAINT PRESTAMOS_USUARIOS
FOREIGN KEY(ID_DEUDA) REFERENCES ZAPATERIA.ABONO_PRESTAMO(ID)
ON DELETE CASCADE ON UPDATE CASCADE


);

CREATE TABLE ABONO_PRESTAMO(
ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
ID_USUARIO BIGINT(18) UNSIGNED NOT NULL,
TOTAL_PRESTAMO DECIMAL(21,2) NOT NULL DEFAULT 0,
TOTAL_DEBE DECIMAL(21,2) NOT NULL DEFAULT 0,
TOTAL_ABONADO DECIMAL (21,2)NOT NULL DEFAULT 0,
CONSTRAINT ID_ABONOUS 
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID)
ON DELETE CASCADE ON UPDATE CASCADE

);
CREATE TABLE LIQUIDACION(
ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
ID_USUARIO BIGINT(18) UNSIGNED NOT NULL,
FECHA_SALIDA DATE NOT NULL DEFAULT CURRENT_DATE,
HORAS_TRABAJADAS BIGINT(18)NOT NULL DEFAULT 0,
DIAS_TRABAJADOS BIGINT(18) NOT NULL,
FECHA_INGRESO DATE NOT NULL, 
SUELDO_BASICO DECIMAL(21,2) NOT NULL DEFAULT 0,
CESANTIAS DECIMAL(21,2) NOT NULL DEFAULT 0,
INTERESES_CESANTIAS DECIMAL(21,2)NOT NULL DEFAULT 0,
PRIMA_SERVICIO DECIMAL(21,2) NOT NULL DEFAULT 0,
VACACIONES DECIMAL(21,2) NOT NULL DEFAULT 0,
VALOR_LIQUIDACION DECIMAL(21,2) NOT NULL DEFAULT 0,
BONIFICACION DECIMAL(21,2) NOT NULL DEFAULT 0,
CONSTRAINT ID_LIQUIDACION
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID)
ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE PRESTAMOS (
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  CLAVE INT(10),
  FECHA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONCEPTO VARCHAR(50),
  VALOR DECIMAL(21,2),
  TOTABONO DECIMAL(21,2),
  AUXILIAR1 INT(10),
  AUXILIAR2 INT(10),
  SALDON DECIMAL(21,2),
  NOMINAS_ID BIGINT(18) UNSIGNED NOT NULL,
  CONSTRAINT NOMINA_PRESTAMOS
  FOREIGN KEY(NOMINAS_ID) REFERENCES NOMINAS(ID)
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ANT_NOMINAS (
    ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    FECHA TIMESTAMP NOT NULL,
    SALARIO DECIMAL(21,2),
    HD INT(10),
    HED INT(10),
    HEN INT(10),
    PRESTAMO DECIMAL(21,2),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    OTROS DECIMAL(21,2),
    NOMINAS_ID BIGINT(18) UNSIGNED NOT NULL,
    CONSTRAINT NOMINA_ANT_NOMINAS
    FOREIGN KEY(NOMINAS_ID) REFERENCES NOMINAS(ID)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE OTRASC (
  COD_CUENTA VARCHAR(2),
  CUENTA VARCHAR(50),
  VALOR DECIMAL(21,2)
);

CREATE TABLE PARAMETROS (
  ID BIGINT(18) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  FECHA_SYS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TRIGGER IF NOT EXITSTS ACCTUALIZAR_PAGOS_FACTURA
AFTER UPDATE ON FACTURAS FOR EACH ROW







-- CREATE UNIQUE INDEX HOLA ON USUARIOS(NOMBRE_USUARIO);

-- INSERTANDO DATOS ---------------------------------------------------------------------------------------------------------------

-- TABLA IMPUESTOS -------------------
INSERT INTO IMPUESTOS(NOMBRE,VALOR) VALUES
('IVA',19);

-- TABLA VISTAS -------------------

INSERT INTO VISTAS (VISTA) VALUES
('USUARIOS'),
('PERMISOS'),
('ROLES'),
('VISTAS'),
('INVENTARIO'),
('NOMINA'),
('VENTAS'),
('COMPRAS'),
('MATERIALES'),
('PROVEEDORES'),
('CLIENTES'),
('MATERIALES USADOS'),
('PAGOS'),
('FACTURAS'),
('IMPUESTOS'),
('PRODUCTOS');

-- TABLA ROLES --------------------
INSERT INTO ROLES (ROL) VALUES 
('ADMINISTRADOR'),
('CONTADOR');

-- TABLA PERMISOS -----------------

INSERT INTO PERMISOS (ROLES_ID,VISTAS_ID) VALUES
(1,1),
(1,2),
(1,3),
(1,4),
(1,5),
(1,6),
(1,7),
(1,8),
(1,9),
(1,10),
(1,11),
(1,12),
(1,13),
(1,14),
(1,15),
(1,16);

-- TABLA USUARIOS ------------------
INSERT INTO ZAPATERIA.USUARIOS(NOMBRES, APELLIDOS, DOCUMENTO, NOMBRE_USUARIO, CONTRASENA, ROLES_ID,TELEFONO,DIRECCION) VALUES
('DIEGO FERNANDO', 'GRISALES VILLA', 1090453553, 'diego', 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3', 1,"",""),
('JHON JAIRO', 'PEREZ CALDERON', 123456, 'JHON', '5994471ABB01112AFCC18159F6CC74B4F511B99806DA59B3CAF5A9C173CACFC5', 1,"423423423432",""),
-- ('OMAR', 'MONTES', 123456, 'OMAR', 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3', 2);